/**
 * Niche Industry Patterns - 150+ industrias de nichos específicos
 * Nichos de mercado muy específicos para máxima personalización
 */

import { IndustryPattern } from './industryPatterns';

export const nicheIndustryPatterns: Record<string, IndustryPattern> = {
  // ==================== NICHOS DE COMIDA ====================
  'vegan-restaurant': {
    id: 'vegan-restaurant',
    name: 'Vegan Restaurant',
    nameEs: 'Restaurante Vegano',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['vegan food', 'plant-based', 'healthy eating', 'organic'],
    ctaText: 'View Menu',
    ctaTextEs: 'Ver Menú',
    keywords: ['vegan', 'plant-based', 'vegano', 'vegetariano', 'saludable']
  },
  'sushi-restaurant': {
    id: 'sushi-restaurant',
    name: 'Sushi Restaurant',
    nameEs: 'Restaurante de Sushi',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'minimal',
    testimonialsVariant: 'masonry',
    colorPalette: 'dark',
    suggestedImages: ['sushi', 'japanese food', 'sashimi', 'chef'],
    ctaText: 'Order Sushi',
    ctaTextEs: 'Pedir Sushi',
    keywords: ['sushi', 'japanese', 'japonés', 'sashimi', 'rolls']
  },
  'pizza-restaurant': {
    id: 'pizza-restaurant',
    name: 'Pizzeria',
    nameEs: 'Pizzería',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['pizza', 'italian food', 'wood oven', 'pizzeria'],
    ctaText: 'Order Pizza',
    ctaTextEs: 'Pedir Pizza',
    keywords: ['pizza', 'pizzeria', 'italian', 'italiano', 'delivery']
  },
  'mexican-restaurant': {
    id: 'mexican-restaurant',
    name: 'Mexican Restaurant',
    nameEs: 'Restaurante Mexicano',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['tacos', 'mexican food', 'margarita', 'guacamole'],
    ctaText: 'Reserve Table',
    ctaTextEs: 'Reservar Mesa',
    keywords: ['mexican', 'tacos', 'mexicano', 'burritos', 'tequila']
  },
  'indian-restaurant': {
    id: 'indian-restaurant',
    name: 'Indian Restaurant',
    nameEs: 'Restaurante Indio',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['indian food', 'curry', 'tandoori', 'spices'],
    ctaText: 'Order Now',
    ctaTextEs: 'Pedir Ahora',
    keywords: ['indian', 'curry', 'indio', 'tandoori', 'masala']
  },
  'thai-restaurant': {
    id: 'thai-restaurant',
    name: 'Thai Restaurant',
    nameEs: 'Restaurante Tailandés',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['thai food', 'pad thai', 'curry', 'asian cuisine'],
    ctaText: 'Order Thai',
    ctaTextEs: 'Pedir Tailandés',
    keywords: ['thai', 'tailandés', 'pad thai', 'curry', 'asian']
  },
  'steakhouse': {
    id: 'steakhouse',
    name: 'Steakhouse',
    nameEs: 'Asador / Steakhouse',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['steak', 'grill', 'meat', 'fine dining'],
    ctaText: 'Reserve Table',
    ctaTextEs: 'Reservar Mesa',
    keywords: ['steakhouse', 'steak', 'asador', 'carne', 'parrilla']
  },
  'seafood-restaurant': {
    id: 'seafood-restaurant',
    name: 'Seafood Restaurant',
    nameEs: 'Restaurante de Mariscos',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['seafood', 'lobster', 'fish', 'ocean'],
    ctaText: 'View Menu',
    ctaTextEs: 'Ver Menú',
    keywords: ['seafood', 'mariscos', 'fish', 'pescado', 'lobster']
  },
  'food-truck': {
    id: 'food-truck',
    name: 'Food Truck',
    nameEs: 'Food Truck',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['food truck', 'street food', 'mobile kitchen', 'outdoor'],
    ctaText: 'Find Us',
    ctaTextEs: 'Encuéntranos',
    keywords: ['food truck', 'street food', 'comida callejera', 'móvil']
  },
  'ice-cream-shop': {
    id: 'ice-cream-shop',
    name: 'Ice Cream Shop',
    nameEs: 'Heladería',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['ice cream', 'gelato', 'dessert', 'colorful'],
    ctaText: 'Visit Us',
    ctaTextEs: 'Visítanos',
    keywords: ['ice cream', 'gelato', 'helado', 'heladería', 'dessert']
  },
  'juice-bar': {
    id: 'juice-bar',
    name: 'Juice Bar',
    nameEs: 'Juice Bar / Jugos',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['fresh juice', 'smoothie', 'fruits', 'healthy'],
    ctaText: 'Order Juice',
    ctaTextEs: 'Pedir Jugo',
    keywords: ['juice', 'smoothie', 'jugo', 'batido', 'healthy']
  },
  'bubble-tea': {
    id: 'bubble-tea',
    name: 'Bubble Tea Shop',
    nameEs: 'Tienda de Bubble Tea',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['bubble tea', 'boba', 'tapioca', 'asian drink'],
    ctaText: 'Order Boba',
    ctaTextEs: 'Pedir Boba',
    keywords: ['bubble tea', 'boba', 'tapioca', 'té de burbujas']
  },
  'donut-shop': {
    id: 'donut-shop',
    name: 'Donut Shop',
    nameEs: 'Tienda de Donuts',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['donuts', 'pastries', 'colorful donuts', 'bakery'],
    ctaText: 'Order Donuts',
    ctaTextEs: 'Pedir Donuts',
    keywords: ['donut', 'doughnut', 'dona', 'bakery', 'pastry']
  },

  // ==================== NICHOS DE BELLEZA ====================
  'lash-studio': {
    id: 'lash-studio',
    name: 'Lash Studio',
    nameEs: 'Estudio de Pestañas',
    category: 'beauty-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['eyelash extensions', 'lash artist', 'beauty', 'eyes'],
    ctaText: 'Book Appointment',
    ctaTextEs: 'Reservar Cita',
    keywords: ['lash', 'eyelash', 'pestañas', 'extensions', 'beauty']
  },
  'brow-studio': {
    id: 'brow-studio',
    name: 'Brow Studio',
    nameEs: 'Estudio de Cejas',
    category: 'beauty-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['eyebrows', 'microblading', 'brow artist', 'beauty'],
    ctaText: 'Book Session',
    ctaTextEs: 'Reservar Sesión',
    keywords: ['brow', 'eyebrow', 'cejas', 'microblading', 'beauty']
  },
  'tattoo-studio': {
    id: 'tattoo-studio',
    name: 'Tattoo Studio',
    nameEs: 'Estudio de Tatuajes',
    category: 'beauty-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['tattoo', 'tattoo artist', 'ink', 'body art'],
    ctaText: 'Book Consultation',
    ctaTextEs: 'Reservar Consulta',
    keywords: ['tattoo', 'tatuaje', 'ink', 'body art', 'artist']
  },
  'piercing-studio': {
    id: 'piercing-studio',
    name: 'Piercing Studio',
    nameEs: 'Estudio de Piercings',
    category: 'beauty-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['piercing', 'jewelry', 'body piercing', 'studio'],
    ctaText: 'Book Piercing',
    ctaTextEs: 'Reservar Piercing',
    keywords: ['piercing', 'body piercing', 'perforación', 'jewelry']
  },
  'waxing-studio': {
    id: 'waxing-studio',
    name: 'Waxing Studio',
    nameEs: 'Estudio de Depilación',
    category: 'beauty-niche',
    sections: ['header', 'hero', 'about', 'features', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'minimal',
    suggestedImages: ['waxing', 'hair removal', 'smooth skin', 'beauty'],
    ctaText: 'Book Waxing',
    ctaTextEs: 'Reservar Depilación',
    keywords: ['waxing', 'hair removal', 'depilación', 'cera', 'beauty']
  },
  'tanning-salon': {
    id: 'tanning-salon',
    name: 'Tanning Salon',
    nameEs: 'Salón de Bronceado',
    category: 'beauty-niche',
    sections: ['header', 'hero', 'about', 'features', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['tanning', 'spray tan', 'bronze skin', 'beauty'],
    ctaText: 'Book Tan',
    ctaTextEs: 'Reservar Bronceado',
    keywords: ['tanning', 'spray tan', 'bronceado', 'sun', 'beauty']
  },
  'makeup-artist': {
    id: 'makeup-artist',
    name: 'Makeup Artist',
    nameEs: 'Maquilladora Profesional',
    category: 'beauty-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['makeup', 'makeup artist', 'beauty', 'bridal makeup'],
    ctaText: 'Book Makeup',
    ctaTextEs: 'Reservar Maquillaje',
    keywords: ['makeup', 'maquillaje', 'artist', 'beauty', 'bridal']
  },
  'hair-extensions': {
    id: 'hair-extensions',
    name: 'Hair Extensions Studio',
    nameEs: 'Estudio de Extensiones',
    category: 'beauty-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'masonry',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['hair extensions', 'long hair', 'beauty', 'salon'],
    ctaText: 'Book Consultation',
    ctaTextEs: 'Reservar Consulta',
    keywords: ['hair extensions', 'extensiones', 'cabello', 'hair', 'beauty']
  },

  // ==================== NICHOS DE FITNESS ====================
  'personal-trainer': {
    id: 'personal-trainer',
    name: 'Personal Trainer',
    nameEs: 'Entrenador Personal',
    category: 'fitness-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['personal trainer', 'fitness', 'workout', 'gym'],
    ctaText: 'Start Training',
    ctaTextEs: 'Empezar Entrenamiento',
    keywords: ['personal trainer', 'entrenador personal', 'fitness', 'workout']
  },
  'nutrition-coach': {
    id: 'nutrition-coach',
    name: 'Nutrition Coach',
    nameEs: 'Coach Nutricional',
    category: 'fitness-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['nutrition', 'healthy food', 'meal prep', 'coach'],
    ctaText: 'Get Started',
    ctaTextEs: 'Comenzar',
    keywords: ['nutrition', 'nutrición', 'coach', 'diet', 'dieta', 'healthy']
  },
  'online-fitness': {
    id: 'online-fitness',
    name: 'Online Fitness Program',
    nameEs: 'Programa de Fitness Online',
    category: 'fitness-niche',
    sections: ['header', 'hero', 'features', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'video',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['online workout', 'home fitness', 'video training', 'app'],
    ctaText: 'Join Program',
    ctaTextEs: 'Unirse al Programa',
    keywords: ['online fitness', 'fitness online', 'home workout', 'programa']
  },
  'spin-studio': {
    id: 'spin-studio',
    name: 'Spin / Cycling Studio',
    nameEs: 'Estudio de Spinning',
    category: 'fitness-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['spin class', 'cycling', 'indoor bike', 'fitness'],
    ctaText: 'Book Class',
    ctaTextEs: 'Reservar Clase',
    keywords: ['spin', 'cycling', 'spinning', 'ciclismo', 'bike']
  },
  'barre-studio': {
    id: 'barre-studio',
    name: 'Barre Studio',
    nameEs: 'Estudio de Barre',
    category: 'fitness-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'minimal',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['barre class', 'ballet fitness', 'workout', 'studio'],
    ctaText: 'Book Class',
    ctaTextEs: 'Reservar Clase',
    keywords: ['barre', 'ballet', 'fitness', 'workout', 'studio']
  },
  'hiit-studio': {
    id: 'hiit-studio',
    name: 'HIIT / Bootcamp Studio',
    nameEs: 'Estudio HIIT / Bootcamp',
    category: 'fitness-niche',
    sections: ['header', 'hero', 'features', 'gallery', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['hiit workout', 'bootcamp', 'intense training', 'fitness'],
    ctaText: 'Join Class',
    ctaTextEs: 'Unirse a Clase',
    keywords: ['hiit', 'bootcamp', 'high intensity', 'entrenamiento', 'fitness']
  },

  // ==================== NICHOS DE MASCOTAS ====================
  'dog-grooming': {
    id: 'dog-grooming',
    name: 'Dog Grooming',
    nameEs: 'Peluquería Canina',
    category: 'pets-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'warm',
    suggestedImages: ['dog grooming', 'cute dog', 'pet salon', 'groomer'],
    ctaText: 'Book Grooming',
    ctaTextEs: 'Reservar Peluquería',
    keywords: ['dog grooming', 'peluquería canina', 'pet', 'perro', 'grooming']
  },
  'dog-training': {
    id: 'dog-training',
    name: 'Dog Training',
    nameEs: 'Entrenamiento Canino',
    category: 'pets-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['dog training', 'obedience', 'trainer', 'puppy'],
    ctaText: 'Start Training',
    ctaTextEs: 'Empezar Entrenamiento',
    keywords: ['dog training', 'entrenamiento canino', 'obedience', 'perro']
  },
  'dog-walking': {
    id: 'dog-walking',
    name: 'Dog Walking Service',
    nameEs: 'Servicio de Paseo de Perros',
    category: 'pets-niche',
    sections: ['header', 'hero', 'about', 'features', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['dog walking', 'dogs park', 'pet care', 'walker'],
    ctaText: 'Book Walk',
    ctaTextEs: 'Reservar Paseo',
    keywords: ['dog walking', 'paseo de perros', 'pet care', 'walker']
  },
  'pet-sitting': {
    id: 'pet-sitting',
    name: 'Pet Sitting Service',
    nameEs: 'Servicio de Cuidado de Mascotas',
    category: 'pets-niche',
    sections: ['header', 'hero', 'about', 'features', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'warm',
    suggestedImages: ['pet sitting', 'cat', 'dog', 'pet care'],
    ctaText: 'Book Sitter',
    ctaTextEs: 'Reservar Cuidador',
    keywords: ['pet sitting', 'cuidado de mascotas', 'pet care', 'sitter']
  },
  'dog-daycare': {
    id: 'dog-daycare',
    name: 'Dog Daycare',
    nameEs: 'Guardería Canina',
    category: 'pets-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'warm',
    suggestedImages: ['dog daycare', 'dogs playing', 'pet care', 'facility'],
    ctaText: 'Book Daycare',
    ctaTextEs: 'Reservar Guardería',
    keywords: ['dog daycare', 'guardería canina', 'pet care', 'daycare']
  },
  'pet-photography': {
    id: 'pet-photography',
    name: 'Pet Photography',
    nameEs: 'Fotografía de Mascotas',
    category: 'pets-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['pet photography', 'cute pets', 'dog portrait', 'cat portrait'],
    ctaText: 'Book Session',
    ctaTextEs: 'Reservar Sesión',
    keywords: ['pet photography', 'fotografía de mascotas', 'pet portrait', 'foto']
  },

  // ==================== NICHOS DE BODAS ====================
  'wedding-planner': {
    id: 'wedding-planner',
    name: 'Wedding Planner',
    nameEs: 'Organizador de Bodas',
    category: 'wedding-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['wedding', 'bride', 'wedding planning', 'elegant'],
    ctaText: 'Plan Your Wedding',
    ctaTextEs: 'Planifica tu Boda',
    keywords: ['wedding planner', 'organizador de bodas', 'wedding', 'boda']
  },
  'wedding-florist': {
    id: 'wedding-florist',
    name: 'Wedding Florist',
    nameEs: 'Florista de Bodas',
    category: 'wedding-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['wedding flowers', 'bouquet', 'floral arrangement', 'bride'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['wedding florist', 'florista de bodas', 'flowers', 'flores', 'bouquet']
  },
  'wedding-cake': {
    id: 'wedding-cake',
    name: 'Wedding Cake Designer',
    nameEs: 'Diseñador de Pasteles de Boda',
    category: 'wedding-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['wedding cake', 'cake design', 'pastry', 'elegant cake'],
    ctaText: 'Order Cake',
    ctaTextEs: 'Pedir Pastel',
    keywords: ['wedding cake', 'pastel de boda', 'cake', 'pastry', 'dessert']
  },
  'wedding-dj': {
    id: 'wedding-dj',
    name: 'Wedding DJ',
    nameEs: 'DJ de Bodas',
    category: 'wedding-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'grid',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['wedding dj', 'party', 'dance floor', 'music'],
    ctaText: 'Book DJ',
    ctaTextEs: 'Reservar DJ',
    keywords: ['wedding dj', 'dj de bodas', 'music', 'party', 'fiesta']
  },
  'wedding-videographer': {
    id: 'wedding-videographer',
    name: 'Wedding Videographer',
    nameEs: 'Videógrafo de Bodas',
    category: 'wedding-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['wedding video', 'filming', 'camera', 'cinematic'],
    ctaText: 'Book Videographer',
    ctaTextEs: 'Reservar Videógrafo',
    keywords: ['wedding videographer', 'videógrafo de bodas', 'video', 'film']
  },
  'bridal-shop': {
    id: 'bridal-shop',
    name: 'Bridal Shop',
    nameEs: 'Tienda de Novias',
    category: 'wedding-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    colorPalette: 'minimal',
    suggestedImages: ['wedding dress', 'bridal', 'bride', 'elegant'],
    ctaText: 'Book Appointment',
    ctaTextEs: 'Reservar Cita',
    keywords: ['bridal shop', 'tienda de novias', 'wedding dress', 'vestido de novia']
  },
  'wedding-rentals': {
    id: 'wedding-rentals',
    name: 'Wedding Rentals',
    nameEs: 'Alquiler para Bodas',
    category: 'wedding-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'minimal',
    suggestedImages: ['wedding rentals', 'tables', 'chairs', 'decor'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['wedding rentals', 'alquiler para bodas', 'rentals', 'decor']
  },

  // ==================== NICHOS DE NIÑOS ====================
  'kids-party': {
    id: 'kids-party',
    name: 'Kids Party Entertainment',
    nameEs: 'Entretenimiento para Fiestas Infantiles',
    category: 'kids-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['kids party', 'birthday', 'fun', 'entertainment'],
    ctaText: 'Book Party',
    ctaTextEs: 'Reservar Fiesta',
    keywords: ['kids party', 'fiesta infantil', 'birthday', 'cumpleaños', 'entertainment']
  },
  'tutoring': {
    id: 'tutoring',
    name: 'Tutoring Service',
    nameEs: 'Servicio de Tutorías',
    category: 'kids-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['tutoring', 'student', 'learning', 'education'],
    ctaText: 'Start Learning',
    ctaTextEs: 'Empezar a Aprender',
    keywords: ['tutoring', 'tutorías', 'education', 'learning', 'student']
  },
  'kids-sports': {
    id: 'kids-sports',
    name: 'Kids Sports Academy',
    nameEs: 'Academia Deportiva para Niños',
    category: 'kids-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['kids sports', 'soccer', 'basketball', 'children playing'],
    ctaText: 'Enroll Now',
    ctaTextEs: 'Inscribirse',
    keywords: ['kids sports', 'deportes para niños', 'academy', 'children', 'sports']
  },
  'kids-art': {
    id: 'kids-art',
    name: 'Kids Art Classes',
    nameEs: 'Clases de Arte para Niños',
    category: 'kids-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['kids art', 'painting', 'creative', 'children'],
    ctaText: 'Join Class',
    ctaTextEs: 'Unirse a Clase',
    keywords: ['kids art', 'arte para niños', 'painting', 'creative', 'children']
  },
  'summer-camp': {
    id: 'summer-camp',
    name: 'Summer Camp',
    nameEs: 'Campamento de Verano',
    category: 'kids-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'warm',
    suggestedImages: ['summer camp', 'kids outdoor', 'activities', 'nature'],
    ctaText: 'Register Now',
    ctaTextEs: 'Registrarse',
    keywords: ['summer camp', 'campamento de verano', 'kids', 'outdoor', 'activities']
  },

  // ==================== NICHOS DE HOGAR ====================
  'kitchen-remodel': {
    id: 'kitchen-remodel',
    name: 'Kitchen Remodeling',
    nameEs: 'Remodelación de Cocinas',
    category: 'home-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    colorPalette: 'light',
    suggestedImages: ['kitchen remodel', 'modern kitchen', 'renovation', 'design'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['kitchen remodel', 'remodelación de cocinas', 'renovation', 'kitchen']
  },
  'bathroom-remodel': {
    id: 'bathroom-remodel',
    name: 'Bathroom Remodeling',
    nameEs: 'Remodelación de Baños',
    category: 'home-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    colorPalette: 'light',
    suggestedImages: ['bathroom remodel', 'modern bathroom', 'renovation', 'design'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['bathroom remodel', 'remodelación de baños', 'renovation', 'bathroom']
  },
  'closet-organization': {
    id: 'closet-organization',
    name: 'Closet Organization',
    nameEs: 'Organización de Closets',
    category: 'home-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'minimal',
    suggestedImages: ['closet organization', 'wardrobe', 'organized', 'storage'],
    ctaText: 'Get Organized',
    ctaTextEs: 'Organizarse',
    keywords: ['closet organization', 'organización de closets', 'wardrobe', 'storage']
  },
  'home-staging': {
    id: 'home-staging',
    name: 'Home Staging',
    nameEs: 'Home Staging',
    category: 'home-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['home staging', 'interior design', 'real estate', 'decor'],
    ctaText: 'Stage Your Home',
    ctaTextEs: 'Preparar tu Casa',
    keywords: ['home staging', 'staging', 'real estate', 'interior', 'decor']
  },
  'home-automation': {
    id: 'home-automation',
    name: 'Home Automation',
    nameEs: 'Automatización del Hogar',
    category: 'home-niche',
    sections: ['header', 'hero', 'features', 'about', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'dark',
    suggestedImages: ['smart home', 'automation', 'technology', 'connected'],
    ctaText: 'Automate Home',
    ctaTextEs: 'Automatizar Casa',
    keywords: ['home automation', 'automatización del hogar', 'smart home', 'iot']
  },
  'fence-company': {
    id: 'fence-company',
    name: 'Fence Company',
    nameEs: 'Empresa de Cercas',
    category: 'home-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['fence', 'wood fence', 'privacy fence', 'installation'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['fence', 'cerca', 'fencing', 'installation', 'privacy']
  },
  'deck-builder': {
    id: 'deck-builder',
    name: 'Deck Builder',
    nameEs: 'Constructor de Decks',
    category: 'home-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    pricingVariant: 'comparison',
    colorPalette: 'warm',
    suggestedImages: ['deck', 'patio', 'outdoor living', 'wood deck'],
    ctaText: 'Build Deck',
    ctaTextEs: 'Construir Deck',
    keywords: ['deck builder', 'constructor de decks', 'patio', 'outdoor']
  },

  // ==================== NICHOS DE TECNOLOGÍA ====================
  'app-development': {
    id: 'app-development',
    name: 'App Development Agency',
    nameEs: 'Agencia de Desarrollo de Apps',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['app development', 'mobile app', 'coding', 'developer'],
    ctaText: 'Build Your App',
    ctaTextEs: 'Construir tu App',
    keywords: ['app development', 'desarrollo de apps', 'mobile', 'ios', 'android']
  },
  'seo-agency': {
    id: 'seo-agency',
    name: 'SEO Agency',
    nameEs: 'Agencia SEO',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['seo', 'search engine', 'analytics', 'ranking'],
    ctaText: 'Boost Rankings',
    ctaTextEs: 'Mejorar Rankings',
    keywords: ['seo', 'search engine', 'optimization', 'posicionamiento', 'google']
  },
  'social-media-agency': {
    id: 'social-media-agency',
    name: 'Social Media Agency',
    nameEs: 'Agencia de Redes Sociales',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'gallery', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['social media', 'instagram', 'content', 'marketing'],
    ctaText: 'Grow Social',
    ctaTextEs: 'Crecer en Redes',
    keywords: ['social media', 'redes sociales', 'instagram', 'facebook', 'marketing']
  },
  'ecommerce-agency': {
    id: 'ecommerce-agency',
    name: 'E-commerce Agency',
    nameEs: 'Agencia de E-commerce',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['ecommerce', 'online store', 'shopping', 'shopify'],
    ctaText: 'Launch Store',
    ctaTextEs: 'Lanzar Tienda',
    keywords: ['ecommerce', 'e-commerce', 'online store', 'tienda online', 'shopify']
  },
  'email-marketing': {
    id: 'email-marketing',
    name: 'Email Marketing Agency',
    nameEs: 'Agencia de Email Marketing',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['email marketing', 'newsletter', 'inbox', 'campaign'],
    ctaText: 'Start Campaign',
    ctaTextEs: 'Iniciar Campaña',
    keywords: ['email marketing', 'newsletter', 'email', 'campaign', 'automation']
  },
  'ppc-agency': {
    id: 'ppc-agency',
    name: 'PPC / Ads Agency',
    nameEs: 'Agencia de PPC / Publicidad',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['ppc', 'google ads', 'advertising', 'marketing'],
    ctaText: 'Launch Ads',
    ctaTextEs: 'Lanzar Anuncios',
    keywords: ['ppc', 'google ads', 'facebook ads', 'publicidad', 'advertising']
  },
  'content-agency': {
    id: 'content-agency',
    name: 'Content Marketing Agency',
    nameEs: 'Agencia de Marketing de Contenidos',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'gallery', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['content marketing', 'blog', 'writing', 'strategy'],
    ctaText: 'Create Content',
    ctaTextEs: 'Crear Contenido',
    keywords: ['content marketing', 'marketing de contenidos', 'blog', 'copywriting']
  },

  // ==================== NICHOS DE VIAJES ====================
  'adventure-tours': {
    id: 'adventure-tours',
    name: 'Adventure Tours',
    nameEs: 'Tours de Aventura',
    category: 'travel-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'cards3d',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['adventure', 'hiking', 'extreme sports', 'nature'],
    ctaText: 'Book Adventure',
    ctaTextEs: 'Reservar Aventura',
    keywords: ['adventure tours', 'tours de aventura', 'hiking', 'extreme', 'outdoor']
  },
  'eco-tourism': {
    id: 'eco-tourism',
    name: 'Eco Tourism',
    nameEs: 'Ecoturismo',
    category: 'travel-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['eco tourism', 'nature', 'sustainable', 'wildlife'],
    ctaText: 'Explore Nature',
    ctaTextEs: 'Explorar Naturaleza',
    keywords: ['eco tourism', 'ecoturismo', 'sustainable', 'nature', 'wildlife']
  },
  'food-tours': {
    id: 'food-tours',
    name: 'Food Tours',
    nameEs: 'Tours Gastronómicos',
    category: 'travel-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['food tour', 'culinary', 'local food', 'tasting'],
    ctaText: 'Book Food Tour',
    ctaTextEs: 'Reservar Tour',
    keywords: ['food tours', 'tours gastronómicos', 'culinary', 'tasting', 'local food']
  },
  'wine-tours': {
    id: 'wine-tours',
    name: 'Wine Tours',
    nameEs: 'Tours de Vino',
    category: 'travel-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['wine tour', 'vineyard', 'wine tasting', 'winery'],
    ctaText: 'Book Wine Tour',
    ctaTextEs: 'Reservar Tour de Vino',
    keywords: ['wine tours', 'tours de vino', 'vineyard', 'tasting', 'winery']
  },
  'walking-tours': {
    id: 'walking-tours',
    name: 'Walking Tours',
    nameEs: 'Tours a Pie',
    category: 'travel-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['walking tour', 'city tour', 'guide', 'sightseeing'],
    ctaText: 'Book Walking Tour',
    ctaTextEs: 'Reservar Tour',
    keywords: ['walking tours', 'tours a pie', 'city tour', 'sightseeing', 'guide']
  },
  'bike-tours': {
    id: 'bike-tours',
    name: 'Bike Tours',
    nameEs: 'Tours en Bicicleta',
    category: 'travel-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['bike tour', 'cycling', 'bicycle', 'outdoor'],
    ctaText: 'Book Bike Tour',
    ctaTextEs: 'Reservar Tour en Bici',
    keywords: ['bike tours', 'tours en bicicleta', 'cycling', 'bicycle', 'outdoor']
  },
  'scuba-diving': {
    id: 'scuba-diving',
    name: 'Scuba Diving',
    nameEs: 'Buceo',
    category: 'travel-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'cards3d',
    testimonialsVariant: 'video',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['scuba diving', 'underwater', 'coral reef', 'ocean'],
    ctaText: 'Book Dive',
    ctaTextEs: 'Reservar Buceo',
    keywords: ['scuba diving', 'buceo', 'diving', 'underwater', 'ocean']
  },
  'ski-resort': {
    id: 'ski-resort',
    name: 'Ski Resort',
    nameEs: 'Resort de Esquí',
    category: 'travel-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'cards3d',
    testimonialsVariant: 'video',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['ski resort', 'skiing', 'snow', 'mountains'],
    ctaText: 'Book Stay',
    ctaTextEs: 'Reservar Estadía',
    keywords: ['ski resort', 'resort de esquí', 'skiing', 'snow', 'winter']
  },

  // ==================== NICHOS DE EVENTOS ====================
  'corporate-events': {
    id: 'corporate-events',
    name: 'Corporate Events',
    nameEs: 'Eventos Corporativos',
    category: 'events-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['corporate event', 'conference', 'business meeting', 'networking'],
    ctaText: 'Plan Event',
    ctaTextEs: 'Planificar Evento',
    keywords: ['corporate events', 'eventos corporativos', 'conference', 'business']
  },
  'birthday-party': {
    id: 'birthday-party',
    name: 'Birthday Party Planning',
    nameEs: 'Planificación de Cumpleaños',
    category: 'events-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['birthday party', 'celebration', 'balloons', 'cake'],
    ctaText: 'Plan Party',
    ctaTextEs: 'Planificar Fiesta',
    keywords: ['birthday party', 'fiesta de cumpleaños', 'celebration', 'party']
  },
  'baby-shower': {
    id: 'baby-shower',
    name: 'Baby Shower Planning',
    nameEs: 'Planificación de Baby Shower',
    category: 'events-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['baby shower', 'celebration', 'baby', 'party'],
    ctaText: 'Plan Shower',
    ctaTextEs: 'Planificar Baby Shower',
    keywords: ['baby shower', 'celebration', 'baby', 'party', 'planning']
  },
  'graduation-party': {
    id: 'graduation-party',
    name: 'Graduation Party',
    nameEs: 'Fiesta de Graduación',
    category: 'events-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['graduation', 'celebration', 'party', 'achievement'],
    ctaText: 'Plan Graduation',
    ctaTextEs: 'Planificar Graduación',
    keywords: ['graduation party', 'fiesta de graduación', 'celebration', 'achievement']
  },
  'quinceañera': {
    id: 'quinceañera',
    name: 'Quinceañera Planning',
    nameEs: 'Planificación de Quinceañera',
    category: 'events-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['quinceañera', 'celebration', 'dress', 'party'],
    ctaText: 'Plan Quinceañera',
    ctaTextEs: 'Planificar Quinceañera',
    keywords: ['quinceañera', 'quince años', 'celebration', 'party', 'sweet 15']
  },
  'anniversary-party': {
    id: 'anniversary-party',
    name: 'Anniversary Party',
    nameEs: 'Fiesta de Aniversario',
    category: 'events-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['anniversary', 'celebration', 'couple', 'party'],
    ctaText: 'Plan Anniversary',
    ctaTextEs: 'Planificar Aniversario',
    keywords: ['anniversary party', 'fiesta de aniversario', 'celebration', 'couple']
  },
  'retirement-party': {
    id: 'retirement-party',
    name: 'Retirement Party',
    nameEs: 'Fiesta de Jubilación',
    category: 'events-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['retirement', 'celebration', 'party', 'achievement'],
    ctaText: 'Plan Retirement',
    ctaTextEs: 'Planificar Jubilación',
    keywords: ['retirement party', 'fiesta de jubilación', 'celebration', 'achievement']
  },

  // ==================== NICHOS PROFESIONALES ====================
  'life-coach': {
    id: 'life-coach',
    name: 'Life Coach',
    nameEs: 'Coach de Vida',
    category: 'professional-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['life coach', 'motivation', 'success', 'personal growth'],
    ctaText: 'Start Coaching',
    ctaTextEs: 'Empezar Coaching',
    keywords: ['life coach', 'coach de vida', 'coaching', 'personal growth', 'motivation']
  },
  'business-coach': {
    id: 'business-coach',
    name: 'Business Coach',
    nameEs: 'Coach de Negocios',
    category: 'professional-niche',
    sections: ['header', 'hero', 'about', 'features', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['business coach', 'entrepreneur', 'success', 'strategy'],
    ctaText: 'Grow Business',
    ctaTextEs: 'Hacer Crecer Negocio',
    keywords: ['business coach', 'coach de negocios', 'entrepreneur', 'strategy', 'growth']
  },
  'career-coach': {
    id: 'career-coach',
    name: 'Career Coach',
    nameEs: 'Coach de Carrera',
    category: 'professional-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['career coach', 'job search', 'interview', 'professional'],
    ctaText: 'Advance Career',
    ctaTextEs: 'Avanzar Carrera',
    keywords: ['career coach', 'coach de carrera', 'job search', 'interview', 'professional']
  },
  'executive-coach': {
    id: 'executive-coach',
    name: 'Executive Coach',
    nameEs: 'Coach Ejecutivo',
    category: 'professional-niche',
    sections: ['header', 'hero', 'about', 'features', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['executive coach', 'leadership', 'ceo', 'business'],
    ctaText: 'Lead Better',
    ctaTextEs: 'Liderar Mejor',
    keywords: ['executive coach', 'coach ejecutivo', 'leadership', 'ceo', 'management']
  },
  'public-speaker': {
    id: 'public-speaker',
    name: 'Public Speaker',
    nameEs: 'Conferencista',
    category: 'professional-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['public speaker', 'conference', 'stage', 'audience'],
    ctaText: 'Book Speaker',
    ctaTextEs: 'Reservar Conferencista',
    keywords: ['public speaker', 'conferencista', 'keynote', 'conference', 'motivational']
  },
  'consultant-solo': {
    id: 'consultant-solo',
    name: 'Independent Consultant',
    nameEs: 'Consultor Independiente',
    category: 'professional-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['consultant', 'professional', 'business', 'strategy'],
    ctaText: 'Hire Consultant',
    ctaTextEs: 'Contratar Consultor',
    keywords: ['consultant', 'consultor', 'independent', 'freelance', 'expert']
  },
  'freelance-writer': {
    id: 'freelance-writer',
    name: 'Freelance Writer',
    nameEs: 'Escritor Freelance',
    category: 'professional-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['writer', 'writing', 'laptop', 'creative'],
    ctaText: 'Hire Writer',
    ctaTextEs: 'Contratar Escritor',
    keywords: ['freelance writer', 'escritor freelance', 'copywriter', 'content', 'blog']
  },
  'freelance-designer': {
    id: 'freelance-designer',
    name: 'Freelance Designer',
    nameEs: 'Diseñador Freelance',
    category: 'professional-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['designer', 'design', 'creative', 'portfolio'],
    ctaText: 'Hire Designer',
    ctaTextEs: 'Contratar Diseñador',
    keywords: ['freelance designer', 'diseñador freelance', 'graphic design', 'creative', 'portfolio']
  }
};

// ==================== NICHOS ADICIONALES ====================

// Más nichos de comida
const additionalFoodNiches: Record<string, IndustryPattern> = {
  'ramen-restaurant': {
    id: 'ramen-restaurant',
    name: 'Ramen Restaurant',
    nameEs: 'Restaurante de Ramen',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'minimal',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['ramen', 'noodles', 'japanese food', 'broth'],
    ctaText: 'Order Ramen',
    ctaTextEs: 'Pedir Ramen',
    keywords: ['ramen', 'noodles', 'japanese', 'japonés', 'fideos']
  },
  'poke-bowl': {
    id: 'poke-bowl',
    name: 'Poke Bowl Restaurant',
    nameEs: 'Restaurante de Poke',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['poke bowl', 'hawaiian food', 'fresh fish', 'healthy'],
    ctaText: 'Build Your Bowl',
    ctaTextEs: 'Crea tu Bowl',
    keywords: ['poke', 'bowl', 'hawaiian', 'fish', 'healthy']
  },
  'acai-bowl': {
    id: 'acai-bowl',
    name: 'Açaí Bowl Shop',
    nameEs: 'Tienda de Açaí',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['acai bowl', 'superfood', 'healthy', 'fruits'],
    ctaText: 'Order Açaí',
    ctaTextEs: 'Pedir Açaí',
    keywords: ['acai', 'açaí', 'bowl', 'superfood', 'healthy']
  },
  'korean-bbq': {
    id: 'korean-bbq',
    name: 'Korean BBQ',
    nameEs: 'BBQ Coreano',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'dark',
    suggestedImages: ['korean bbq', 'grill', 'meat', 'korean food'],
    ctaText: 'Reserve Table',
    ctaTextEs: 'Reservar Mesa',
    keywords: ['korean bbq', 'bbq coreano', 'grill', 'korean', 'meat']
  },
  'mediterranean': {
    id: 'mediterranean',
    name: 'Mediterranean Restaurant',
    nameEs: 'Restaurante Mediterráneo',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['mediterranean food', 'hummus', 'falafel', 'greek'],
    ctaText: 'View Menu',
    ctaTextEs: 'Ver Menú',
    keywords: ['mediterranean', 'mediterráneo', 'greek', 'hummus', 'falafel']
  },
  'french-bistro': {
    id: 'french-bistro',
    name: 'French Bistro',
    nameEs: 'Bistró Francés',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    colorPalette: 'minimal',
    suggestedImages: ['french food', 'bistro', 'wine', 'elegant'],
    ctaText: 'Reserve Table',
    ctaTextEs: 'Reservar Mesa',
    keywords: ['french', 'bistro', 'francés', 'wine', 'elegant']
  },
  'dim-sum': {
    id: 'dim-sum',
    name: 'Dim Sum Restaurant',
    nameEs: 'Restaurante de Dim Sum',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['dim sum', 'dumplings', 'chinese food', 'steamer'],
    ctaText: 'Reserve Table',
    ctaTextEs: 'Reservar Mesa',
    keywords: ['dim sum', 'dumplings', 'chinese', 'chino', 'steamer']
  },
  'tapas-bar': {
    id: 'tapas-bar',
    name: 'Tapas Bar',
    nameEs: 'Bar de Tapas',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['tapas', 'spanish food', 'wine', 'bar'],
    ctaText: 'Reserve Table',
    ctaTextEs: 'Reservar Mesa',
    keywords: ['tapas', 'spanish', 'español', 'wine', 'bar']
  },
  'brunch-spot': {
    id: 'brunch-spot',
    name: 'Brunch Spot',
    nameEs: 'Lugar de Brunch',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'masonry',
    colorPalette: 'warm',
    suggestedImages: ['brunch', 'eggs benedict', 'pancakes', 'coffee'],
    ctaText: 'Reserve Brunch',
    ctaTextEs: 'Reservar Brunch',
    keywords: ['brunch', 'breakfast', 'desayuno', 'eggs', 'pancakes']
  },
  'dessert-bar': {
    id: 'dessert-bar',
    name: 'Dessert Bar',
    nameEs: 'Bar de Postres',
    category: 'food-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['desserts', 'cakes', 'pastries', 'sweet'],
    ctaText: 'View Desserts',
    ctaTextEs: 'Ver Postres',
    keywords: ['dessert', 'postre', 'cake', 'pastry', 'sweet']
  },

  // Más nichos de salud
  'chiropractor': {
    id: 'chiropractor',
    name: 'Chiropractor',
    nameEs: 'Quiropráctico',
    category: 'health-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['chiropractor', 'spine', 'back pain', 'treatment'],
    ctaText: 'Book Appointment',
    ctaTextEs: 'Reservar Cita',
    keywords: ['chiropractor', 'quiropráctico', 'spine', 'back pain', 'adjustment']
  },
  'acupuncture': {
    id: 'acupuncture',
    name: 'Acupuncture Clinic',
    nameEs: 'Clínica de Acupuntura',
    category: 'health-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['acupuncture', 'needles', 'traditional medicine', 'wellness'],
    ctaText: 'Book Session',
    ctaTextEs: 'Reservar Sesión',
    keywords: ['acupuncture', 'acupuntura', 'traditional', 'wellness', 'healing']
  },
  'physical-therapy': {
    id: 'physical-therapy',
    name: 'Physical Therapy',
    nameEs: 'Fisioterapia',
    category: 'health-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['physical therapy', 'rehabilitation', 'exercise', 'recovery'],
    ctaText: 'Start Recovery',
    ctaTextEs: 'Iniciar Recuperación',
    keywords: ['physical therapy', 'fisioterapia', 'rehabilitation', 'recovery', 'exercise']
  },
  'massage-therapy': {
    id: 'massage-therapy',
    name: 'Massage Therapy',
    nameEs: 'Terapia de Masajes',
    category: 'health-niche',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'warm',
    suggestedImages: ['massage', 'spa', 'relaxation', 'therapy'],
    ctaText: 'Book Massage',
    ctaTextEs: 'Reservar Masaje',
    keywords: ['massage', 'masaje', 'therapy', 'spa', 'relaxation']
  },
  'mental-health': {
    id: 'mental-health',
    name: 'Mental Health Therapist',
    nameEs: 'Terapeuta de Salud Mental',
    category: 'health-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['therapy', 'mental health', 'counseling', 'wellness'],
    ctaText: 'Book Session',
    ctaTextEs: 'Reservar Sesión',
    keywords: ['mental health', 'salud mental', 'therapy', 'counseling', 'psychologist']
  },
  'nutritionist': {
    id: 'nutritionist',
    name: 'Nutritionist',
    nameEs: 'Nutricionista',
    category: 'health-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['nutritionist', 'healthy food', 'diet', 'wellness'],
    ctaText: 'Get Consultation',
    ctaTextEs: 'Obtener Consulta',
    keywords: ['nutritionist', 'nutricionista', 'diet', 'healthy', 'wellness']
  },
  'sleep-clinic': {
    id: 'sleep-clinic',
    name: 'Sleep Clinic',
    nameEs: 'Clínica del Sueño',
    category: 'health-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['sleep', 'bedroom', 'rest', 'health'],
    ctaText: 'Book Consultation',
    ctaTextEs: 'Reservar Consulta',
    keywords: ['sleep clinic', 'clínica del sueño', 'insomnia', 'rest', 'health']
  },
  'fertility-clinic': {
    id: 'fertility-clinic',
    name: 'Fertility Clinic',
    nameEs: 'Clínica de Fertilidad',
    category: 'health-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'stats', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    colorPalette: 'minimal',
    suggestedImages: ['fertility', 'family', 'baby', 'medical'],
    ctaText: 'Schedule Consultation',
    ctaTextEs: 'Programar Consulta',
    keywords: ['fertility', 'fertilidad', 'ivf', 'family', 'baby']
  },

  // Más nichos de servicios profesionales
  'immigration-lawyer': {
    id: 'immigration-lawyer',
    name: 'Immigration Lawyer',
    nameEs: 'Abogado de Inmigración',
    category: 'legal-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['immigration', 'passport', 'visa', 'lawyer'],
    ctaText: 'Free Consultation',
    ctaTextEs: 'Consulta Gratis',
    keywords: ['immigration', 'inmigración', 'visa', 'lawyer', 'abogado']
  },
  'family-lawyer': {
    id: 'family-lawyer',
    name: 'Family Lawyer',
    nameEs: 'Abogado de Familia',
    category: 'legal-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'light',
    suggestedImages: ['family', 'lawyer', 'divorce', 'custody'],
    ctaText: 'Free Consultation',
    ctaTextEs: 'Consulta Gratis',
    keywords: ['family lawyer', 'abogado de familia', 'divorce', 'custody', 'legal']
  },
  'personal-injury': {
    id: 'personal-injury',
    name: 'Personal Injury Lawyer',
    nameEs: 'Abogado de Lesiones Personales',
    category: 'legal-niche',
    sections: ['header', 'hero', 'about', 'features', 'stats', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['lawyer', 'accident', 'injury', 'justice'],
    ctaText: 'Free Case Review',
    ctaTextEs: 'Revisión Gratis',
    keywords: ['personal injury', 'lesiones personales', 'accident', 'lawyer', 'compensation']
  },
  'criminal-defense': {
    id: 'criminal-defense',
    name: 'Criminal Defense Lawyer',
    nameEs: 'Abogado Defensor Penal',
    category: 'legal-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['lawyer', 'courtroom', 'defense', 'justice'],
    ctaText: 'Free Consultation',
    ctaTextEs: 'Consulta Gratis',
    keywords: ['criminal defense', 'defensa penal', 'lawyer', 'court', 'legal']
  },
  'estate-planning': {
    id: 'estate-planning',
    name: 'Estate Planning Attorney',
    nameEs: 'Abogado de Planificación Patrimonial',
    category: 'legal-niche',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['estate planning', 'will', 'trust', 'family'],
    ctaText: 'Plan Your Estate',
    ctaTextEs: 'Planifica tu Patrimonio',
    keywords: ['estate planning', 'planificación patrimonial', 'will', 'trust', 'inheritance']
  },

  // Más nichos de tecnología
  'blockchain': {
    id: 'blockchain',
    name: 'Blockchain Development',
    nameEs: 'Desarrollo Blockchain',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['blockchain', 'crypto', 'decentralized', 'technology'],
    ctaText: 'Build on Blockchain',
    ctaTextEs: 'Construir en Blockchain',
    keywords: ['blockchain', 'crypto', 'web3', 'smart contracts', 'decentralized']
  },
  'data-analytics': {
    id: 'data-analytics',
    name: 'Data Analytics Agency',
    nameEs: 'Agencia de Análisis de Datos',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['data analytics', 'charts', 'dashboard', 'insights'],
    ctaText: 'Unlock Insights',
    ctaTextEs: 'Desbloquear Insights',
    keywords: ['data analytics', 'análisis de datos', 'business intelligence', 'insights', 'dashboard']
  },
  'cloud-services': {
    id: 'cloud-services',
    name: 'Cloud Services Provider',
    nameEs: 'Proveedor de Servicios Cloud',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['cloud computing', 'servers', 'infrastructure', 'technology'],
    ctaText: 'Move to Cloud',
    ctaTextEs: 'Migrar a la Nube',
    keywords: ['cloud services', 'servicios cloud', 'aws', 'azure', 'infrastructure']
  },
  'iot-solutions': {
    id: 'iot-solutions',
    name: 'IoT Solutions',
    nameEs: 'Soluciones IoT',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['iot', 'connected devices', 'sensors', 'smart'],
    ctaText: 'Connect Everything',
    ctaTextEs: 'Conectar Todo',
    keywords: ['iot', 'internet of things', 'connected', 'smart devices', 'sensors']
  },
  'vr-ar': {
    id: 'vr-ar',
    name: 'VR/AR Development',
    nameEs: 'Desarrollo VR/AR',
    category: 'tech-niche',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'cards3d',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['vr', 'ar', 'virtual reality', 'immersive'],
    ctaText: 'Build Immersive',
    ctaTextEs: 'Crear Inmersivo',
    keywords: ['vr', 'ar', 'virtual reality', 'augmented reality', 'immersive']
  },

  // Más nichos de retail
  'jewelry-store': {
    id: 'jewelry-store',
    name: 'Jewelry Store',
    nameEs: 'Joyería',
    category: 'retail-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    colorPalette: 'minimal',
    suggestedImages: ['jewelry', 'diamonds', 'rings', 'luxury'],
    ctaText: 'Shop Collection',
    ctaTextEs: 'Ver Colección',
    keywords: ['jewelry', 'joyería', 'diamonds', 'rings', 'luxury']
  },
  'watch-store': {
    id: 'watch-store',
    name: 'Watch Store',
    nameEs: 'Tienda de Relojes',
    category: 'retail-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    colorPalette: 'dark',
    suggestedImages: ['watches', 'luxury watch', 'timepiece', 'elegant'],
    ctaText: 'Shop Watches',
    ctaTextEs: 'Ver Relojes',
    keywords: ['watch', 'reloj', 'timepiece', 'luxury', 'elegant']
  },
  'eyewear-store': {
    id: 'eyewear-store',
    name: 'Eyewear Store',
    nameEs: 'Óptica',
    category: 'retail-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'minimal',
    suggestedImages: ['eyewear', 'glasses', 'sunglasses', 'optical'],
    ctaText: 'Shop Eyewear',
    ctaTextEs: 'Ver Gafas',
    keywords: ['eyewear', 'glasses', 'gafas', 'optical', 'sunglasses']
  },
  'shoe-store': {
    id: 'shoe-store',
    name: 'Shoe Store',
    nameEs: 'Zapatería',
    category: 'retail-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['shoes', 'sneakers', 'footwear', 'fashion'],
    ctaText: 'Shop Shoes',
    ctaTextEs: 'Ver Zapatos',
    keywords: ['shoes', 'zapatos', 'sneakers', 'footwear', 'fashion']
  },
  'vintage-shop': {
    id: 'vintage-shop',
    name: 'Vintage Shop',
    nameEs: 'Tienda Vintage',
    category: 'retail-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['vintage', 'retro', 'antique', 'thrift'],
    ctaText: 'Shop Vintage',
    ctaTextEs: 'Ver Vintage',
    keywords: ['vintage', 'retro', 'antique', 'thrift', 'secondhand']
  },
  'plant-shop': {
    id: 'plant-shop',
    name: 'Plant Shop',
    nameEs: 'Tienda de Plantas',
    category: 'retail-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['plants', 'indoor plants', 'greenery', 'botanical'],
    ctaText: 'Shop Plants',
    ctaTextEs: 'Ver Plantas',
    keywords: ['plants', 'plantas', 'indoor plants', 'botanical', 'greenery']
  },
  'candle-shop': {
    id: 'candle-shop',
    name: 'Candle Shop',
    nameEs: 'Tienda de Velas',
    category: 'retail-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['candles', 'aromatherapy', 'home decor', 'cozy'],
    ctaText: 'Shop Candles',
    ctaTextEs: 'Ver Velas',
    keywords: ['candles', 'velas', 'aromatherapy', 'home decor', 'scented']
  },
  'gift-shop': {
    id: 'gift-shop',
    name: 'Gift Shop',
    nameEs: 'Tienda de Regalos',
    category: 'retail-niche',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['gifts', 'presents', 'wrapping', 'celebration'],
    ctaText: 'Find Perfect Gift',
    ctaTextEs: 'Encontrar Regalo Perfecto',
    keywords: ['gift shop', 'tienda de regalos', 'presents', 'gifts', 'celebration']
  }
};

// Combinar con los patrones existentes
Object.assign(nicheIndustryPatterns, additionalFoodNiches);

// Exportar el conteo total de patrones de nicho (después de combinar)
export const TOTAL_NICHE_PATTERNS = Object.keys(nicheIndustryPatterns).length;
