/**
 * Extended Industry Patterns - 250+ industrias adicionales
 * Basado en clasificación NAICS + nichos de mercado específicos
 */

import { IndustryPattern } from './industryPatterns';

export const extendedIndustryPatterns: Record<string, IndustryPattern> = {
  // ==================== AGRICULTURA Y ALIMENTACIÓN ====================
  'organic-farm': {
    id: 'organic-farm',
    name: 'Organic Farm',
    nameEs: 'Granja Orgánica',
    category: 'agriculture',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'process', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    colorPalette: 'warm',
    suggestedImages: ['organic vegetables', 'farm field', 'sustainable farming', 'fresh produce'],
    ctaText: 'Shop Fresh',
    ctaTextEs: 'Comprar Fresco',
    keywords: ['organic', 'farm', 'vegetables', 'orgánico', 'granja', 'verduras', 'huerto']
  },
  'vineyard': {
    id: 'vineyard',
    name: 'Vineyard / Wine Estate',
    nameEs: 'Viñedo / Bodega',
    category: 'agriculture',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'process', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['vineyard', 'wine bottles', 'grape harvest', 'wine cellar'],
    ctaText: 'Book Tasting',
    ctaTextEs: 'Reservar Cata',
    keywords: ['vineyard', 'wine', 'winery', 'viñedo', 'vino', 'bodega', 'cata']
  },
  'beekeeping': {
    id: 'beekeeping',
    name: 'Beekeeping / Honey',
    nameEs: 'Apicultura / Miel',
    category: 'agriculture',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'cta', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['beehive', 'honey jar', 'beekeeper', 'honeycomb'],
    ctaText: 'Buy Honey',
    ctaTextEs: 'Comprar Miel',
    keywords: ['beekeeping', 'honey', 'bees', 'apicultura', 'miel', 'abejas']
  },
  'mushroom-farm': {
    id: 'mushroom-farm',
    name: 'Mushroom Farm',
    nameEs: 'Cultivo de Hongos',
    category: 'agriculture',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    colorPalette: 'minimal',
    suggestedImages: ['mushrooms', 'mushroom farm', 'gourmet mushrooms', 'cultivation'],
    ctaText: 'Order Now',
    ctaTextEs: 'Pedir Ahora',
    keywords: ['mushroom', 'fungi', 'cultivation', 'hongos', 'setas', 'cultivo']
  },
  'fish-farm': {
    id: 'fish-farm',
    name: 'Fish Farm / Aquaculture',
    nameEs: 'Piscifactoría / Acuicultura',
    category: 'agriculture',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'stats', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'light',
    suggestedImages: ['fish farm', 'aquaculture', 'salmon', 'fish tanks'],
    ctaText: 'Contact Us',
    ctaTextEs: 'Contáctanos',
    keywords: ['fish farm', 'aquaculture', 'salmon', 'piscifactoría', 'acuicultura', 'pescado']
  },
  'dairy-farm': {
    id: 'dairy-farm',
    name: 'Dairy Farm',
    nameEs: 'Granja Lechera',
    category: 'agriculture',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'carousel',
    colorPalette: 'light',
    suggestedImages: ['dairy farm', 'cows', 'milk', 'cheese'],
    ctaText: 'Visit Farm',
    ctaTextEs: 'Visitar Granja',
    keywords: ['dairy', 'milk', 'cheese', 'lechería', 'leche', 'queso', 'granja']
  },
  'greenhouse': {
    id: 'greenhouse',
    name: 'Greenhouse / Nursery',
    nameEs: 'Invernadero / Vivero',
    category: 'agriculture',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['greenhouse', 'plants', 'nursery', 'seedlings'],
    ctaText: 'Shop Plants',
    ctaTextEs: 'Comprar Plantas',
    keywords: ['greenhouse', 'nursery', 'plants', 'invernadero', 'vivero', 'plantas']
  },
  'florist': {
    id: 'florist',
    name: 'Florist',
    nameEs: 'Floristería',
    category: 'agriculture',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['flower bouquet', 'florist shop', 'roses', 'flower arrangement'],
    ctaText: 'Order Flowers',
    ctaTextEs: 'Pedir Flores',
    keywords: ['florist', 'flowers', 'bouquet', 'floristería', 'flores', 'ramo']
  },

  // ==================== MANUFACTURA ====================
  'furniture-maker': {
    id: 'furniture-maker',
    name: 'Furniture Maker',
    nameEs: 'Fabricante de Muebles',
    category: 'manufacturing',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'process', 'testimonials', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    colorPalette: 'warm',
    suggestedImages: ['handmade furniture', 'woodworking', 'craftsman', 'custom furniture'],
    ctaText: 'Custom Order',
    ctaTextEs: 'Pedido Personalizado',
    keywords: ['furniture', 'woodworking', 'custom', 'muebles', 'carpintería', 'madera']
  },
  'textile-manufacturer': {
    id: 'textile-manufacturer',
    name: 'Textile Manufacturer',
    nameEs: 'Fabricante Textil',
    category: 'manufacturing',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'stats', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'light',
    suggestedImages: ['textile factory', 'fabric rolls', 'weaving', 'textile production'],
    ctaText: 'Request Quote',
    ctaTextEs: 'Solicitar Cotización',
    keywords: ['textile', 'fabric', 'manufacturing', 'textil', 'tela', 'fabricación']
  },
  'metal-fabrication': {
    id: 'metal-fabrication',
    name: 'Metal Fabrication',
    nameEs: 'Fabricación Metálica',
    category: 'manufacturing',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'stats', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    colorPalette: 'dark',
    suggestedImages: ['metal fabrication', 'welding', 'steel', 'industrial'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['metal', 'fabrication', 'welding', 'metal', 'fabricación', 'soldadura']
  },
  'packaging': {
    id: 'packaging',
    name: 'Packaging Company',
    nameEs: 'Empresa de Empaques',
    category: 'manufacturing',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'stats', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'bento',
    testimonialsVariant: 'grid',
    colorPalette: 'light',
    suggestedImages: ['packaging', 'boxes', 'sustainable packaging', 'custom boxes'],
    ctaText: 'Request Sample',
    ctaTextEs: 'Solicitar Muestra',
    keywords: ['packaging', 'boxes', 'empaques', 'cajas', 'empaque', 'envases']
  },
  'printing-company': {
    id: 'printing-company',
    name: 'Printing Company',
    nameEs: 'Imprenta',
    category: 'manufacturing',
    sections: ['header', 'hero', 'features', 'gallery', 'stats', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['printing press', 'printed materials', 'business cards', 'brochures'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['printing', 'print', 'imprenta', 'impresión', 'tarjetas', 'folletos']
  },
  'plastics-manufacturer': {
    id: 'plastics-manufacturer',
    name: 'Plastics Manufacturer',
    nameEs: 'Fabricante de Plásticos',
    category: 'manufacturing',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'stats', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    colorPalette: 'light',
    suggestedImages: ['plastic manufacturing', 'injection molding', 'plastic products', 'factory'],
    ctaText: 'Contact Us',
    ctaTextEs: 'Contáctanos',
    keywords: ['plastics', 'manufacturing', 'injection', 'plásticos', 'fabricación', 'inyección']
  },
  'electronics-manufacturer': {
    id: 'electronics-manufacturer',
    name: 'Electronics Manufacturer',
    nameEs: 'Fabricante de Electrónicos',
    category: 'manufacturing',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'stats', 'testimonials', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['electronics factory', 'circuit boards', 'assembly line', 'tech manufacturing'],
    ctaText: 'Partner With Us',
    ctaTextEs: 'Asóciate Con Nosotros',
    keywords: ['electronics', 'manufacturing', 'pcb', 'electrónicos', 'fabricación', 'circuitos']
  },
  'cosmetics-manufacturer': {
    id: 'cosmetics-manufacturer',
    name: 'Cosmetics Manufacturer',
    nameEs: 'Fabricante de Cosméticos',
    category: 'manufacturing',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['cosmetics lab', 'beauty products', 'skincare', 'makeup production'],
    ctaText: 'Private Label',
    ctaTextEs: 'Marca Privada',
    keywords: ['cosmetics', 'beauty', 'skincare', 'cosméticos', 'belleza', 'cuidado de piel']
  },

  // ==================== COMERCIO MINORISTA ====================
  'bookstore': {
    id: 'bookstore',
    name: 'Bookstore',
    nameEs: 'Librería',
    category: 'retail',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'masonry',
    colorPalette: 'warm',
    suggestedImages: ['bookstore', 'books', 'reading', 'library'],
    ctaText: 'Browse Books',
    ctaTextEs: 'Ver Libros',
    keywords: ['bookstore', 'books', 'reading', 'librería', 'libros', 'lectura']
  },
  'toy-store': {
    id: 'toy-store',
    name: 'Toy Store',
    nameEs: 'Juguetería',
    category: 'retail',
    sections: ['header', 'hero', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['toy store', 'toys', 'children playing', 'games'],
    ctaText: 'Shop Toys',
    ctaTextEs: 'Comprar Juguetes',
    keywords: ['toys', 'games', 'children', 'juguetes', 'juegos', 'niños']
  },
  'sporting-goods': {
    id: 'sporting-goods',
    name: 'Sporting Goods Store',
    nameEs: 'Tienda de Deportes',
    category: 'retail',
    sections: ['header', 'hero', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['sports equipment', 'athletic gear', 'fitness', 'outdoor sports'],
    ctaText: 'Shop Now',
    ctaTextEs: 'Comprar Ahora',
    keywords: ['sports', 'equipment', 'fitness', 'deportes', 'equipamiento', 'fitness']
  },
  'electronics-store': {
    id: 'electronics-store',
    name: 'Electronics Store',
    nameEs: 'Tienda de Electrónicos',
    category: 'retail',
    sections: ['header', 'hero', 'features', 'gallery', 'stats', 'testimonials', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    colorPalette: 'dark',
    suggestedImages: ['electronics', 'gadgets', 'tech store', 'smartphones'],
    ctaText: 'Shop Tech',
    ctaTextEs: 'Comprar Tech',
    keywords: ['electronics', 'gadgets', 'tech', 'electrónicos', 'tecnología', 'gadgets']
  },
  'furniture-store': {
    id: 'furniture-store',
    name: 'Furniture Store',
    nameEs: 'Tienda de Muebles',
    category: 'retail',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    colorPalette: 'minimal',
    suggestedImages: ['furniture showroom', 'living room', 'modern furniture', 'home decor'],
    ctaText: 'Shop Furniture',
    ctaTextEs: 'Comprar Muebles',
    keywords: ['furniture', 'home', 'decor', 'muebles', 'hogar', 'decoración']
  },
  'wine-shop': {
    id: 'wine-shop',
    name: 'Wine Shop',
    nameEs: 'Vinoteca',
    category: 'retail',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'warm',
    suggestedImages: ['wine shop', 'wine bottles', 'wine cellar', 'sommelier'],
    ctaText: 'Shop Wines',
    ctaTextEs: 'Comprar Vinos',
    keywords: ['wine', 'shop', 'sommelier', 'vino', 'vinoteca', 'bodega']
  },
  'organic-store': {
    id: 'organic-store',
    name: 'Organic / Health Food Store',
    nameEs: 'Tienda Orgánica / Naturista',
    category: 'retail',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'warm',
    suggestedImages: ['organic store', 'health food', 'natural products', 'vegetables'],
    ctaText: 'Shop Organic',
    ctaTextEs: 'Comprar Orgánico',
    keywords: ['organic', 'health', 'natural', 'orgánico', 'salud', 'natural', 'naturista']
  },
  'gift-shop': {
    id: 'gift-shop',
    name: 'Gift Shop',
    nameEs: 'Tienda de Regalos',
    category: 'retail',
    sections: ['header', 'hero', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['gift shop', 'presents', 'souvenirs', 'gift boxes'],
    ctaText: 'Find Gifts',
    ctaTextEs: 'Encontrar Regalos',
    keywords: ['gifts', 'presents', 'souvenirs', 'regalos', 'obsequios', 'recuerdos']
  },
  'antique-shop': {
    id: 'antique-shop',
    name: 'Antique Shop',
    nameEs: 'Tienda de Antigüedades',
    category: 'retail',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'minimal',
    testimonialsVariant: 'masonry',
    colorPalette: 'warm',
    suggestedImages: ['antique shop', 'vintage items', 'collectibles', 'antique furniture'],
    ctaText: 'Browse Collection',
    ctaTextEs: 'Ver Colección',
    keywords: ['antiques', 'vintage', 'collectibles', 'antigüedades', 'vintage', 'coleccionables']
  },
  'art-gallery': {
    id: 'art-gallery',
    name: 'Art Gallery',
    nameEs: 'Galería de Arte',
    category: 'retail',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'minimal',
    testimonialsVariant: 'masonry',
    colorPalette: 'minimal',
    suggestedImages: ['art gallery', 'paintings', 'sculpture', 'exhibition'],
    ctaText: 'View Exhibition',
    ctaTextEs: 'Ver Exposición',
    keywords: ['art', 'gallery', 'paintings', 'arte', 'galería', 'pinturas', 'exposición']
  },

  // ==================== SERVICIOS FINANCIEROS ====================
  'insurance-agency': {
    id: 'insurance-agency',
    name: 'Insurance Agency',
    nameEs: 'Agencia de Seguros',
    category: 'finance',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['insurance', 'family protection', 'security', 'coverage'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['insurance', 'coverage', 'protection', 'seguros', 'cobertura', 'protección']
  },
  'mortgage-broker': {
    id: 'mortgage-broker',
    name: 'Mortgage Broker',
    nameEs: 'Broker Hipotecario',
    category: 'finance',
    sections: ['header', 'hero', 'features', 'about', 'process', 'stats', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'light',
    suggestedImages: ['mortgage', 'home buying', 'keys', 'family home'],
    ctaText: 'Calculate Rate',
    ctaTextEs: 'Calcular Tasa',
    keywords: ['mortgage', 'home loan', 'broker', 'hipoteca', 'préstamo', 'vivienda']
  },
  'investment-advisor': {
    id: 'investment-advisor',
    name: 'Investment Advisor',
    nameEs: 'Asesor de Inversiones',
    category: 'finance',
    sections: ['header', 'hero', 'about', 'features', 'stats', 'testimonials', 'process', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['investment', 'wealth management', 'portfolio', 'financial planning'],
    ctaText: 'Schedule Consultation',
    ctaTextEs: 'Agendar Consulta',
    keywords: ['investment', 'advisor', 'wealth', 'inversiones', 'asesor', 'patrimonio']
  },
  'credit-union': {
    id: 'credit-union',
    name: 'Credit Union',
    nameEs: 'Cooperativa de Crédito',
    category: 'finance',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['credit union', 'banking', 'community', 'savings'],
    ctaText: 'Join Today',
    ctaTextEs: 'Únete Hoy',
    keywords: ['credit union', 'banking', 'savings', 'cooperativa', 'crédito', 'ahorro']
  },
  'tax-preparation': {
    id: 'tax-preparation',
    name: 'Tax Preparation Service',
    nameEs: 'Servicio de Preparación de Impuestos',
    category: 'finance',
    sections: ['header', 'hero', 'features', 'about', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['tax preparation', 'documents', 'calculator', 'tax forms'],
    ctaText: 'File Taxes',
    ctaTextEs: 'Declarar Impuestos',
    keywords: ['tax', 'preparation', 'filing', 'impuestos', 'declaración', 'fiscal']
  },
  'cryptocurrency': {
    id: 'cryptocurrency',
    name: 'Cryptocurrency Exchange',
    nameEs: 'Exchange de Criptomonedas',
    category: 'finance',
    sections: ['header', 'hero', 'features', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['cryptocurrency', 'bitcoin', 'blockchain', 'trading'],
    ctaText: 'Start Trading',
    ctaTextEs: 'Empezar a Operar',
    keywords: ['crypto', 'bitcoin', 'exchange', 'cripto', 'bitcoin', 'trading']
  },

  // ==================== SERVICIOS PROFESIONALES ====================
  'translation-service': {
    id: 'translation-service',
    name: 'Translation Service',
    nameEs: 'Servicio de Traducción',
    category: 'services',
    sections: ['header', 'hero', 'features', 'about', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['translation', 'languages', 'documents', 'global'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['translation', 'languages', 'interpreter', 'traducción', 'idiomas', 'intérprete']
  },
  'notary-public': {
    id: 'notary-public',
    name: 'Notary Public',
    nameEs: 'Notaría',
    category: 'services',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['notary', 'documents', 'legal', 'signing'],
    ctaText: 'Schedule Appointment',
    ctaTextEs: 'Agendar Cita',
    keywords: ['notary', 'legal', 'documents', 'notaría', 'legal', 'documentos']
  },
  'private-investigator': {
    id: 'private-investigator',
    name: 'Private Investigator',
    nameEs: 'Investigador Privado',
    category: 'services',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['detective', 'investigation', 'surveillance', 'evidence'],
    ctaText: 'Free Consultation',
    ctaTextEs: 'Consulta Gratis',
    keywords: ['investigator', 'detective', 'surveillance', 'investigador', 'detective', 'vigilancia']
  },
  'security-company': {
    id: 'security-company',
    name: 'Security Company',
    nameEs: 'Empresa de Seguridad',
    category: 'services',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'comparison',
    colorPalette: 'dark',
    suggestedImages: ['security guard', 'surveillance', 'protection', 'alarm system'],
    ctaText: 'Get Protected',
    ctaTextEs: 'Protégete',
    keywords: ['security', 'guard', 'protection', 'seguridad', 'vigilancia', 'protección']
  },
  'staffing-agency': {
    id: 'staffing-agency',
    name: 'Staffing Agency',
    nameEs: 'Agencia de Empleo',
    category: 'services',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'light',
    suggestedImages: ['staffing', 'hiring', 'job interview', 'recruitment'],
    ctaText: 'Find Talent',
    ctaTextEs: 'Encontrar Talento',
    keywords: ['staffing', 'hiring', 'recruitment', 'empleo', 'contratación', 'reclutamiento']
  },
  'courier-service': {
    id: 'courier-service',
    name: 'Courier Service',
    nameEs: 'Servicio de Mensajería',
    category: 'services',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['courier', 'delivery', 'package', 'fast delivery'],
    ctaText: 'Ship Now',
    ctaTextEs: 'Enviar Ahora',
    keywords: ['courier', 'delivery', 'shipping', 'mensajería', 'envío', 'paquetería']
  },
  'moving-company': {
    id: 'moving-company',
    name: 'Moving Company',
    nameEs: 'Empresa de Mudanzas',
    category: 'services',
    sections: ['header', 'hero', 'features', 'about', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['moving truck', 'boxes', 'movers', 'new home'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['moving', 'relocation', 'movers', 'mudanzas', 'traslado', 'mudanza']
  },
  'storage-facility': {
    id: 'storage-facility',
    name: 'Storage Facility',
    nameEs: 'Almacén de Autoservicio',
    category: 'services',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['storage units', 'warehouse', 'self storage', 'boxes'],
    ctaText: 'Reserve Unit',
    ctaTextEs: 'Reservar Unidad',
    keywords: ['storage', 'self storage', 'warehouse', 'almacén', 'bodega', 'guardamuebles']
  },

  // ==================== SALUD Y BIENESTAR ====================
  'chiropractor': {
    id: 'chiropractor',
    name: 'Chiropractor',
    nameEs: 'Quiropráctico',
    category: 'health',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['chiropractor', 'spine', 'adjustment', 'wellness'],
    ctaText: 'Book Adjustment',
    ctaTextEs: 'Agendar Ajuste',
    keywords: ['chiropractor', 'spine', 'adjustment', 'quiropráctico', 'columna', 'ajuste']
  },
  'physical-therapy': {
    id: 'physical-therapy',
    name: 'Physical Therapy',
    nameEs: 'Fisioterapia',
    category: 'health',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['physical therapy', 'rehabilitation', 'exercise', 'recovery'],
    ctaText: 'Start Recovery',
    ctaTextEs: 'Iniciar Recuperación',
    keywords: ['physical therapy', 'rehabilitation', 'fisioterapia', 'rehabilitación', 'terapia']
  },
  'acupuncture': {
    id: 'acupuncture',
    name: 'Acupuncture Clinic',
    nameEs: 'Clínica de Acupuntura',
    category: 'health',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'minimal',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['acupuncture', 'needles', 'traditional medicine', 'wellness'],
    ctaText: 'Book Session',
    ctaTextEs: 'Reservar Sesión',
    keywords: ['acupuncture', 'traditional', 'wellness', 'acupuntura', 'tradicional', 'bienestar']
  },
  'optometrist': {
    id: 'optometrist',
    name: 'Optometrist',
    nameEs: 'Optometrista',
    category: 'health',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['eye exam', 'glasses', 'optometrist', 'vision'],
    ctaText: 'Book Eye Exam',
    ctaTextEs: 'Agendar Examen',
    keywords: ['optometrist', 'eye', 'glasses', 'optometrista', 'ojos', 'lentes', 'óptica']
  },
  'dermatologist': {
    id: 'dermatologist',
    name: 'Dermatologist',
    nameEs: 'Dermatólogo',
    category: 'health',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['dermatologist', 'skin care', 'treatment', 'clinic'],
    ctaText: 'Book Consultation',
    ctaTextEs: 'Agendar Consulta',
    keywords: ['dermatologist', 'skin', 'treatment', 'dermatólogo', 'piel', 'tratamiento']
  },
  'plastic-surgery': {
    id: 'plastic-surgery',
    name: 'Plastic Surgery Clinic',
    nameEs: 'Clínica de Cirugía Plástica',
    category: 'health',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['plastic surgery', 'cosmetic', 'beauty', 'clinic'],
    ctaText: 'Free Consultation',
    ctaTextEs: 'Consulta Gratis',
    keywords: ['plastic surgery', 'cosmetic', 'cirugía plástica', 'estética', 'cosmético']
  },
  'mental-health': {
    id: 'mental-health',
    name: 'Mental Health Clinic',
    nameEs: 'Clínica de Salud Mental',
    category: 'health',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['therapy', 'mental health', 'counseling', 'wellness'],
    ctaText: 'Get Help',
    ctaTextEs: 'Obtener Ayuda',
    keywords: ['mental health', 'therapy', 'counseling', 'salud mental', 'terapia', 'psicología']
  },
  'addiction-treatment': {
    id: 'addiction-treatment',
    name: 'Addiction Treatment Center',
    nameEs: 'Centro de Tratamiento de Adicciones',
    category: 'health',
    sections: ['header', 'hero', 'about', 'features', 'process', 'stats', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'minimal',
    suggestedImages: ['recovery', 'support', 'treatment', 'healing'],
    ctaText: 'Get Help Now',
    ctaTextEs: 'Obtener Ayuda',
    keywords: ['addiction', 'treatment', 'recovery', 'adicción', 'tratamiento', 'recuperación']
  },
  'senior-care': {
    id: 'senior-care',
    name: 'Senior Care / Assisted Living',
    nameEs: 'Cuidado de Adultos Mayores',
    category: 'health',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'comparison',
    colorPalette: 'warm',
    suggestedImages: ['senior care', 'elderly', 'assisted living', 'caregiver'],
    ctaText: 'Schedule Tour',
    ctaTextEs: 'Agendar Visita',
    keywords: ['senior care', 'elderly', 'assisted living', 'adultos mayores', 'asistencia', 'cuidado']
  },
  'home-care': {
    id: 'home-care',
    name: 'Home Care Service',
    nameEs: 'Servicio de Cuidado en Casa',
    category: 'health',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['home care', 'caregiver', 'elderly care', 'nursing'],
    ctaText: 'Get Care',
    ctaTextEs: 'Obtener Cuidado',
    keywords: ['home care', 'caregiver', 'nursing', 'cuidado en casa', 'enfermería', 'asistencia']
  },

  // ==================== TECNOLOGÍA ====================
  'web-development': {
    id: 'web-development',
    name: 'Web Development Agency',
    nameEs: 'Agencia de Desarrollo Web',
    category: 'technology',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['web development', 'coding', 'website design', 'developer'],
    ctaText: 'Start Project',
    ctaTextEs: 'Iniciar Proyecto',
    keywords: ['web development', 'website', 'coding', 'desarrollo web', 'sitio web', 'programación']
  },
  'it-support': {
    id: 'it-support',
    name: 'IT Support / MSP',
    nameEs: 'Soporte de TI',
    category: 'technology',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'comparison',
    colorPalette: 'dark',
    suggestedImages: ['it support', 'tech support', 'computer repair', 'network'],
    ctaText: 'Get Support',
    ctaTextEs: 'Obtener Soporte',
    keywords: ['it support', 'tech support', 'msp', 'soporte técnico', 'ti', 'informática']
  },
  'cloud-services': {
    id: 'cloud-services',
    name: 'Cloud Services Provider',
    nameEs: 'Proveedor de Servicios en la Nube',
    category: 'technology',
    sections: ['header', 'hero', 'features', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'featured',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['cloud computing', 'servers', 'data center', 'infrastructure'],
    ctaText: 'Get Started',
    ctaTextEs: 'Comenzar',
    keywords: ['cloud', 'hosting', 'infrastructure', 'nube', 'hosting', 'infraestructura']
  },
  'data-analytics': {
    id: 'data-analytics',
    name: 'Data Analytics Company',
    nameEs: 'Empresa de Análisis de Datos',
    category: 'technology',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['data analytics', 'dashboard', 'charts', 'business intelligence'],
    ctaText: 'Get Insights',
    ctaTextEs: 'Obtener Insights',
    keywords: ['data analytics', 'business intelligence', 'análisis de datos', 'inteligencia de negocios']
  },
  'iot-solutions': {
    id: 'iot-solutions',
    name: 'IoT Solutions',
    nameEs: 'Soluciones IoT',
    category: 'technology',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['iot', 'smart devices', 'connected', 'sensors'],
    ctaText: 'Connect Now',
    ctaTextEs: 'Conectar Ahora',
    keywords: ['iot', 'smart', 'connected', 'internet de las cosas', 'inteligente', 'conectado']
  },
  'blockchain': {
    id: 'blockchain',
    name: 'Blockchain Solutions',
    nameEs: 'Soluciones Blockchain',
    category: 'technology',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'featured',
    colorPalette: 'neon',
    suggestedImages: ['blockchain', 'cryptocurrency', 'decentralized', 'technology'],
    ctaText: 'Build on Blockchain',
    ctaTextEs: 'Construir en Blockchain',
    keywords: ['blockchain', 'crypto', 'decentralized', 'descentralizado', 'cripto']
  },
  'vr-ar': {
    id: 'vr-ar',
    name: 'VR/AR Development',
    nameEs: 'Desarrollo VR/AR',
    category: 'technology',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'stats', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['virtual reality', 'augmented reality', 'vr headset', 'immersive'],
    ctaText: 'Experience VR',
    ctaTextEs: 'Experimentar VR',
    keywords: ['vr', 'ar', 'virtual reality', 'realidad virtual', 'realidad aumentada']
  },
  'robotics': {
    id: 'robotics',
    name: 'Robotics Company',
    nameEs: 'Empresa de Robótica',
    category: 'technology',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'stats', 'process', 'testimonials', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['robotics', 'automation', 'robot arm', 'manufacturing'],
    ctaText: 'Automate Now',
    ctaTextEs: 'Automatizar Ahora',
    keywords: ['robotics', 'automation', 'robot', 'robótica', 'automatización']
  },

  // ==================== EDUCACIÓN ====================
  'music-school': {
    id: 'music-school',
    name: 'Music School',
    nameEs: 'Escuela de Música',
    category: 'education',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['music school', 'piano', 'guitar', 'music lesson'],
    ctaText: 'Start Learning',
    ctaTextEs: 'Empezar a Aprender',
    keywords: ['music', 'school', 'lessons', 'música', 'escuela', 'clases']
  },
  'dance-studio': {
    id: 'dance-studio',
    name: 'Dance Studio',
    nameEs: 'Estudio de Danza',
    category: 'education',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['dance studio', 'ballet', 'dancers', 'dance class'],
    ctaText: 'Join Class',
    ctaTextEs: 'Unirse a Clase',
    keywords: ['dance', 'studio', 'ballet', 'danza', 'estudio', 'baile']
  },
  'art-school': {
    id: 'art-school',
    name: 'Art School',
    nameEs: 'Escuela de Arte',
    category: 'education',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'masonry',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['art school', 'painting', 'drawing', 'art class'],
    ctaText: 'Enroll Now',
    ctaTextEs: 'Inscribirse',
    keywords: ['art', 'school', 'painting', 'arte', 'escuela', 'pintura']
  },
  'cooking-school': {
    id: 'cooking-school',
    name: 'Cooking School',
    nameEs: 'Escuela de Cocina',
    category: 'education',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'warm',
    suggestedImages: ['cooking class', 'chef', 'kitchen', 'culinary'],
    ctaText: 'Book Class',
    ctaTextEs: 'Reservar Clase',
    keywords: ['cooking', 'culinary', 'chef', 'cocina', 'culinario', 'gastronomía']
  },
  'driving-school': {
    id: 'driving-school',
    name: 'Driving School',
    nameEs: 'Autoescuela',
    category: 'education',
    sections: ['header', 'hero', 'features', 'about', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['driving school', 'car', 'driving lesson', 'instructor'],
    ctaText: 'Start Driving',
    ctaTextEs: 'Empezar a Conducir',
    keywords: ['driving', 'school', 'license', 'autoescuela', 'conducir', 'licencia']
  },
  'test-prep': {
    id: 'test-prep',
    name: 'Test Preparation',
    nameEs: 'Preparación de Exámenes',
    category: 'education',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['test prep', 'studying', 'exam', 'education'],
    ctaText: 'Start Prep',
    ctaTextEs: 'Empezar Preparación',
    keywords: ['test prep', 'sat', 'gmat', 'preparación', 'examen', 'estudiar']
  },
  'coding-bootcamp': {
    id: 'coding-bootcamp',
    name: 'Coding Bootcamp',
    nameEs: 'Bootcamp de Programación',
    category: 'education',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['coding bootcamp', 'programming', 'developer', 'laptop'],
    ctaText: 'Apply Now',
    ctaTextEs: 'Aplicar Ahora',
    keywords: ['coding', 'bootcamp', 'programming', 'programación', 'desarrollo', 'código']
  },

  // ==================== ENTRETENIMIENTO ====================
  'escape-room': {
    id: 'escape-room',
    name: 'Escape Room',
    nameEs: 'Escape Room',
    category: 'entertainment',
    sections: ['header', 'hero', 'features', 'gallery', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['escape room', 'puzzle', 'mystery', 'adventure'],
    ctaText: 'Book Room',
    ctaTextEs: 'Reservar Sala',
    keywords: ['escape room', 'puzzle', 'adventure', 'escape', 'acertijo', 'aventura']
  },
  'trampoline-park': {
    id: 'trampoline-park',
    name: 'Trampoline Park',
    nameEs: 'Parque de Trampolines',
    category: 'entertainment',
    sections: ['header', 'hero', 'features', 'gallery', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['trampoline park', 'jumping', 'fun', 'kids'],
    ctaText: 'Jump Now',
    ctaTextEs: 'Saltar Ahora',
    keywords: ['trampoline', 'park', 'jump', 'trampolín', 'parque', 'saltar']
  },
  'laser-tag': {
    id: 'laser-tag',
    name: 'Laser Tag Arena',
    nameEs: 'Arena de Laser Tag',
    category: 'entertainment',
    sections: ['header', 'hero', 'features', 'gallery', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['laser tag', 'arena', 'gaming', 'action'],
    ctaText: 'Book Session',
    ctaTextEs: 'Reservar Sesión',
    keywords: ['laser tag', 'arena', 'gaming', 'laser', 'juego', 'acción']
  },
  'bowling-alley': {
    id: 'bowling-alley',
    name: 'Bowling Alley',
    nameEs: 'Bolera',
    category: 'entertainment',
    sections: ['header', 'hero', 'features', 'gallery', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['bowling', 'bowling alley', 'pins', 'fun'],
    ctaText: 'Book Lane',
    ctaTextEs: 'Reservar Pista',
    keywords: ['bowling', 'alley', 'lanes', 'boliche', 'bolera', 'pista']
  },
  'mini-golf': {
    id: 'mini-golf',
    name: 'Mini Golf',
    nameEs: 'Mini Golf',
    category: 'entertainment',
    sections: ['header', 'hero', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['mini golf', 'putt putt', 'golf course', 'family fun'],
    ctaText: 'Play Now',
    ctaTextEs: 'Jugar Ahora',
    keywords: ['mini golf', 'putt putt', 'golf', 'minigolf', 'diversión']
  },
  'karaoke-bar': {
    id: 'karaoke-bar',
    name: 'Karaoke Bar',
    nameEs: 'Bar de Karaoke',
    category: 'entertainment',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['karaoke', 'singing', 'microphone', 'party'],
    ctaText: 'Book Room',
    ctaTextEs: 'Reservar Sala',
    keywords: ['karaoke', 'singing', 'bar', 'cantar', 'fiesta']
  },
  'comedy-club': {
    id: 'comedy-club',
    name: 'Comedy Club',
    nameEs: 'Club de Comedia',
    category: 'entertainment',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['comedy club', 'stand up', 'comedian', 'stage'],
    ctaText: 'Get Tickets',
    ctaTextEs: 'Comprar Entradas',
    keywords: ['comedy', 'stand up', 'club', 'comedia', 'humor']
  },
  'nightclub': {
    id: 'nightclub',
    name: 'Nightclub',
    nameEs: 'Discoteca',
    category: 'entertainment',
    sections: ['header', 'hero', 'about', 'gallery', 'features', 'testimonials', 'pricing', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'neon',
    suggestedImages: ['nightclub', 'dj', 'dance floor', 'party'],
    ctaText: 'Reserve Table',
    ctaTextEs: 'Reservar Mesa',
    keywords: ['nightclub', 'club', 'party', 'discoteca', 'fiesta', 'baile']
  },

  // ==================== DEPORTES ====================
  'martial-arts': {
    id: 'martial-arts',
    name: 'Martial Arts School',
    nameEs: 'Escuela de Artes Marciales',
    category: 'sports',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['martial arts', 'karate', 'dojo', 'training'],
    ctaText: 'Start Training',
    ctaTextEs: 'Empezar Entrenamiento',
    keywords: ['martial arts', 'karate', 'judo', 'artes marciales', 'karate', 'defensa']
  },
  'swimming-pool': {
    id: 'swimming-pool',
    name: 'Swimming Pool / Aquatic Center',
    nameEs: 'Piscina / Centro Acuático',
    category: 'sports',
    sections: ['header', 'hero', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['swimming pool', 'swimming', 'aquatic center', 'water'],
    ctaText: 'Join Now',
    ctaTextEs: 'Unirse Ahora',
    keywords: ['swimming', 'pool', 'aquatic', 'piscina', 'natación', 'acuático']
  },
  'tennis-club': {
    id: 'tennis-club',
    name: 'Tennis Club',
    nameEs: 'Club de Tenis',
    category: 'sports',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['tennis court', 'tennis player', 'racket', 'club'],
    ctaText: 'Book Court',
    ctaTextEs: 'Reservar Cancha',
    keywords: ['tennis', 'club', 'court', 'tenis', 'cancha', 'raqueta']
  },
  'golf-club': {
    id: 'golf-club',
    name: 'Golf Club',
    nameEs: 'Club de Golf',
    category: 'sports',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['golf course', 'golfer', 'golf club', 'green'],
    ctaText: 'Book Tee Time',
    ctaTextEs: 'Reservar Salida',
    keywords: ['golf', 'club', 'course', 'campo', 'green']
  },
  'climbing-gym': {
    id: 'climbing-gym',
    name: 'Climbing Gym',
    nameEs: 'Gimnasio de Escalada',
    category: 'sports',
    sections: ['header', 'hero', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['climbing gym', 'rock climbing', 'bouldering', 'climber'],
    ctaText: 'Start Climbing',
    ctaTextEs: 'Empezar a Escalar',
    keywords: ['climbing', 'gym', 'bouldering', 'escalada', 'gimnasio', 'boulder']
  },
  'crossfit': {
    id: 'crossfit',
    name: 'CrossFit Box',
    nameEs: 'Box de CrossFit',
    category: 'sports',
    sections: ['header', 'hero', 'features', 'gallery', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['crossfit', 'workout', 'gym', 'fitness'],
    ctaText: 'Join Box',
    ctaTextEs: 'Unirse al Box',
    keywords: ['crossfit', 'workout', 'fitness', 'entrenamiento', 'gimnasio']
  },
  'pilates-studio': {
    id: 'pilates-studio',
    name: 'Pilates Studio',
    nameEs: 'Estudio de Pilates',
    category: 'sports',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'minimal',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'minimal',
    suggestedImages: ['pilates', 'studio', 'reformer', 'exercise'],
    ctaText: 'Book Class',
    ctaTextEs: 'Reservar Clase',
    keywords: ['pilates', 'studio', 'reformer', 'estudio', 'ejercicio']
  },
  'boxing-gym': {
    id: 'boxing-gym',
    name: 'Boxing Gym',
    nameEs: 'Gimnasio de Boxeo',
    category: 'sports',
    sections: ['header', 'hero', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['boxing gym', 'boxer', 'ring', 'training'],
    ctaText: 'Start Training',
    ctaTextEs: 'Empezar Entrenamiento',
    keywords: ['boxing', 'gym', 'training', 'boxeo', 'gimnasio', 'entrenamiento']
  },

  // ==================== HOGAR Y JARDÍN ====================
  'landscaping': {
    id: 'landscaping',
    name: 'Landscaping Company',
    nameEs: 'Empresa de Jardinería',
    category: 'home',
    sections: ['header', 'hero', 'features', 'about', 'gallery', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'warm',
    suggestedImages: ['landscaping', 'garden', 'lawn', 'outdoor'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['landscaping', 'garden', 'lawn', 'jardinería', 'jardín', 'césped']
  },
  'pool-service': {
    id: 'pool-service',
    name: 'Pool Service',
    nameEs: 'Servicio de Piscinas',
    category: 'home',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['pool service', 'swimming pool', 'maintenance', 'cleaning'],
    ctaText: 'Get Service',
    ctaTextEs: 'Obtener Servicio',
    keywords: ['pool', 'service', 'maintenance', 'piscina', 'servicio', 'mantenimiento']
  },
  'pest-control': {
    id: 'pest-control',
    name: 'Pest Control',
    nameEs: 'Control de Plagas',
    category: 'home',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['pest control', 'exterminator', 'home protection', 'insects'],
    ctaText: 'Get Inspection',
    ctaTextEs: 'Obtener Inspección',
    keywords: ['pest control', 'exterminator', 'control de plagas', 'fumigación', 'insectos']
  },
  'cleaning-service': {
    id: 'cleaning-service',
    name: 'Cleaning Service',
    nameEs: 'Servicio de Limpieza',
    category: 'home',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['cleaning service', 'house cleaning', 'maid', 'spotless'],
    ctaText: 'Book Cleaning',
    ctaTextEs: 'Reservar Limpieza',
    keywords: ['cleaning', 'service', 'maid', 'limpieza', 'servicio', 'hogar']
  },
  'window-cleaning': {
    id: 'window-cleaning',
    name: 'Window Cleaning',
    nameEs: 'Limpieza de Ventanas',
    category: 'home',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['window cleaning', 'glass', 'squeegee', 'clean windows'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['window', 'cleaning', 'glass', 'ventanas', 'limpieza', 'cristales']
  },
  'carpet-cleaning': {
    id: 'carpet-cleaning',
    name: 'Carpet Cleaning',
    nameEs: 'Limpieza de Alfombras',
    category: 'home',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['carpet cleaning', 'steam cleaning', 'upholstery', 'clean carpet'],
    ctaText: 'Book Cleaning',
    ctaTextEs: 'Reservar Limpieza',
    keywords: ['carpet', 'cleaning', 'upholstery', 'alfombras', 'limpieza', 'tapicería']
  },
  'handyman': {
    id: 'handyman',
    name: 'Handyman Service',
    nameEs: 'Servicio de Mantenimiento',
    category: 'home',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['handyman', 'tools', 'repair', 'home improvement'],
    ctaText: 'Book Service',
    ctaTextEs: 'Reservar Servicio',
    keywords: ['handyman', 'repair', 'maintenance', 'mantenimiento', 'reparación', 'hogar']
  },
  'locksmith': {
    id: 'locksmith',
    name: 'Locksmith',
    nameEs: 'Cerrajería',
    category: 'home',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['locksmith', 'keys', 'lock', 'security'],
    ctaText: 'Call Now',
    ctaTextEs: 'Llamar Ahora',
    keywords: ['locksmith', 'keys', 'lock', 'cerrajería', 'llaves', 'cerraduras']
  },
  'garage-door': {
    id: 'garage-door',
    name: 'Garage Door Service',
    nameEs: 'Servicio de Puertas de Garaje',
    category: 'home',
    sections: ['header', 'hero', 'features', 'about', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    pricingVariant: 'comparison',
    colorPalette: 'light',
    suggestedImages: ['garage door', 'installation', 'repair', 'opener'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['garage door', 'repair', 'installation', 'puerta de garaje', 'reparación', 'instalación']
  },

  // ==================== TRANSPORTE ====================
  'trucking': {
    id: 'trucking',
    name: 'Trucking Company',
    nameEs: 'Empresa de Transporte',
    category: 'transportation',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['trucking', 'semi truck', 'freight', 'logistics'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['trucking', 'freight', 'logistics', 'transporte', 'carga', 'logística']
  },
  'taxi-service': {
    id: 'taxi-service',
    name: 'Taxi Service',
    nameEs: 'Servicio de Taxi',
    category: 'transportation',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['taxi', 'cab', 'driver', 'transportation'],
    ctaText: 'Book Ride',
    ctaTextEs: 'Reservar Viaje',
    keywords: ['taxi', 'cab', 'ride', 'taxi', 'transporte', 'viaje']
  },
  'limo-service': {
    id: 'limo-service',
    name: 'Limousine Service',
    nameEs: 'Servicio de Limusina',
    category: 'transportation',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['limousine', 'luxury car', 'chauffeur', 'vip'],
    ctaText: 'Book Limo',
    ctaTextEs: 'Reservar Limusina',
    keywords: ['limousine', 'limo', 'luxury', 'limusina', 'lujo', 'chofer']
  },
  'shuttle-service': {
    id: 'shuttle-service',
    name: 'Shuttle Service',
    nameEs: 'Servicio de Shuttle',
    category: 'transportation',
    sections: ['header', 'hero', 'features', 'about', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['shuttle', 'airport transfer', 'van', 'transportation'],
    ctaText: 'Book Shuttle',
    ctaTextEs: 'Reservar Shuttle',
    keywords: ['shuttle', 'airport', 'transfer', 'shuttle', 'aeropuerto', 'traslado']
  },
  'boat-charter': {
    id: 'boat-charter',
    name: 'Boat Charter',
    nameEs: 'Alquiler de Barcos',
    category: 'transportation',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'alternating',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['yacht', 'boat charter', 'sailing', 'ocean'],
    ctaText: 'Charter Now',
    ctaTextEs: 'Alquilar Ahora',
    keywords: ['boat', 'charter', 'yacht', 'barco', 'yate', 'alquiler']
  },
  'helicopter-tours': {
    id: 'helicopter-tours',
    name: 'Helicopter Tours',
    nameEs: 'Tours en Helicóptero',
    category: 'transportation',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'cards3d',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['helicopter', 'aerial view', 'tour', 'scenic'],
    ctaText: 'Book Tour',
    ctaTextEs: 'Reservar Tour',
    keywords: ['helicopter', 'tour', 'aerial', 'helicóptero', 'tour', 'aéreo']
  },

  // ==================== MEDIOS Y COMUNICACIÓN ====================
  'video-production': {
    id: 'video-production',
    name: 'Video Production',
    nameEs: 'Producción de Video',
    category: 'media',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'alternating',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['video production', 'camera', 'filming', 'studio'],
    ctaText: 'Start Project',
    ctaTextEs: 'Iniciar Proyecto',
    keywords: ['video', 'production', 'filming', 'video', 'producción', 'filmación']
  },
  'animation-studio': {
    id: 'animation-studio',
    name: 'Animation Studio',
    nameEs: 'Estudio de Animación',
    category: 'media',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'animated',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['animation', 'studio', '3d', 'motion graphics'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['animation', 'studio', '3d', 'animación', 'estudio', 'motion']
  },
  'recording-studio': {
    id: 'recording-studio',
    name: 'Recording Studio',
    nameEs: 'Estudio de Grabación',
    category: 'media',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'dark',
    suggestedImages: ['recording studio', 'microphone', 'mixing console', 'music'],
    ctaText: 'Book Session',
    ctaTextEs: 'Reservar Sesión',
    keywords: ['recording', 'studio', 'music', 'grabación', 'estudio', 'música']
  },
  'radio-station': {
    id: 'radio-station',
    name: 'Radio Station',
    nameEs: 'Estación de Radio',
    category: 'media',
    sections: ['header', 'hero', 'about', 'features', 'gallery', 'testimonials', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    colorPalette: 'gradient',
    suggestedImages: ['radio station', 'dj', 'broadcasting', 'microphone'],
    ctaText: 'Listen Live',
    ctaTextEs: 'Escuchar en Vivo',
    keywords: ['radio', 'station', 'broadcasting', 'radio', 'estación', 'transmisión']
  },
  'pr-agency': {
    id: 'pr-agency',
    name: 'PR Agency',
    nameEs: 'Agencia de Relaciones Públicas',
    category: 'media',
    sections: ['header', 'hero', 'about', 'features', 'logocloud', 'stats', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['pr agency', 'media', 'press', 'communication'],
    ctaText: 'Get PR',
    ctaTextEs: 'Obtener PR',
    keywords: ['pr', 'public relations', 'media', 'relaciones públicas', 'prensa', 'comunicación']
  },
  'influencer-agency': {
    id: 'influencer-agency',
    name: 'Influencer Marketing Agency',
    nameEs: 'Agencia de Marketing de Influencers',
    category: 'media',
    sections: ['header', 'hero', 'about', 'features', 'stats', 'gallery', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'asymmetric',
    featuresVariant: 'bento',
    testimonialsVariant: 'video',
    pricingVariant: 'cards',
    colorPalette: 'gradient',
    suggestedImages: ['influencer', 'social media', 'content creator', 'marketing'],
    ctaText: 'Start Campaign',
    ctaTextEs: 'Iniciar Campaña',
    keywords: ['influencer', 'marketing', 'social media', 'influencer', 'redes sociales', 'contenido']
  },

  // ==================== ENERGÍA Y MEDIO AMBIENTE ====================
  'solar-energy': {
    id: 'solar-energy',
    name: 'Solar Energy Company',
    nameEs: 'Empresa de Energía Solar',
    category: 'energy',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['solar panels', 'renewable energy', 'sun', 'green energy'],
    ctaText: 'Get Quote',
    ctaTextEs: 'Obtener Cotización',
    keywords: ['solar', 'energy', 'renewable', 'solar', 'energía', 'renovable']
  },
  'wind-energy': {
    id: 'wind-energy',
    name: 'Wind Energy Company',
    nameEs: 'Empresa de Energía Eólica',
    category: 'energy',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'centered',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'gradient',
    suggestedImages: ['wind turbines', 'wind farm', 'renewable energy', 'green'],
    ctaText: 'Learn More',
    ctaTextEs: 'Saber Más',
    keywords: ['wind', 'energy', 'turbine', 'eólica', 'energía', 'turbina']
  },
  'recycling': {
    id: 'recycling',
    name: 'Recycling Company',
    nameEs: 'Empresa de Reciclaje',
    category: 'energy',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'grid',
    colorPalette: 'warm',
    suggestedImages: ['recycling', 'sustainability', 'green', 'environment'],
    ctaText: 'Schedule Pickup',
    ctaTextEs: 'Agendar Recolección',
    keywords: ['recycling', 'waste', 'sustainability', 'reciclaje', 'residuos', 'sostenibilidad']
  },
  'ev-charging': {
    id: 'ev-charging',
    name: 'EV Charging Stations',
    nameEs: 'Estaciones de Carga EV',
    category: 'energy',
    sections: ['header', 'hero', 'features', 'about', 'stats', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'animated',
    testimonialsVariant: 'carousel',
    pricingVariant: 'comparison',
    colorPalette: 'gradient',
    suggestedImages: ['ev charging', 'electric car', 'charging station', 'green'],
    ctaText: 'Find Station',
    ctaTextEs: 'Encontrar Estación',
    keywords: ['ev', 'charging', 'electric', 'carga', 'eléctrico', 'estación']
  },
  'environmental-consulting': {
    id: 'environmental-consulting',
    name: 'Environmental Consulting',
    nameEs: 'Consultoría Ambiental',
    category: 'energy',
    sections: ['header', 'hero', 'about', 'features', 'stats', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'warm',
    suggestedImages: ['environment', 'consulting', 'sustainability', 'nature'],
    ctaText: 'Get Assessment',
    ctaTextEs: 'Obtener Evaluación',
    keywords: ['environmental', 'consulting', 'sustainability', 'ambiental', 'consultoría', 'sostenibilidad']
  },

  // ==================== SERVICIOS LEGALES ====================
  'immigration-lawyer': {
    id: 'immigration-lawyer',
    name: 'Immigration Lawyer',
    nameEs: 'Abogado de Inmigración',
    category: 'legal',
    sections: ['header', 'hero', 'about', 'features', 'process', 'stats', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'light',
    suggestedImages: ['immigration', 'lawyer', 'passport', 'visa'],
    ctaText: 'Free Consultation',
    ctaTextEs: 'Consulta Gratis',
    keywords: ['immigration', 'lawyer', 'visa', 'inmigración', 'abogado', 'visa']
  },
  'personal-injury': {
    id: 'personal-injury',
    name: 'Personal Injury Lawyer',
    nameEs: 'Abogado de Lesiones Personales',
    category: 'legal',
    sections: ['header', 'hero', 'about', 'features', 'stats', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['personal injury', 'lawyer', 'justice', 'accident'],
    ctaText: 'Free Case Review',
    ctaTextEs: 'Revisión Gratis',
    keywords: ['personal injury', 'lawyer', 'accident', 'lesiones personales', 'abogado', 'accidente']
  },
  'family-lawyer': {
    id: 'family-lawyer',
    name: 'Family Lawyer',
    nameEs: 'Abogado de Familia',
    category: 'legal',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'light',
    suggestedImages: ['family law', 'lawyer', 'family', 'divorce'],
    ctaText: 'Schedule Consultation',
    ctaTextEs: 'Agendar Consulta',
    keywords: ['family', 'lawyer', 'divorce', 'familia', 'abogado', 'divorcio']
  },
  'criminal-defense': {
    id: 'criminal-defense',
    name: 'Criminal Defense Lawyer',
    nameEs: 'Abogado Penalista',
    category: 'legal',
    sections: ['header', 'hero', 'about', 'features', 'stats', 'process', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'dark',
    suggestedImages: ['criminal defense', 'lawyer', 'courtroom', 'justice'],
    ctaText: 'Get Defense',
    ctaTextEs: 'Obtener Defensa',
    keywords: ['criminal', 'defense', 'lawyer', 'penal', 'defensa', 'abogado']
  },
  'estate-planning': {
    id: 'estate-planning',
    name: 'Estate Planning Attorney',
    nameEs: 'Abogado de Planificación Patrimonial',
    category: 'legal',
    sections: ['header', 'hero', 'about', 'features', 'process', 'testimonials', 'pricing', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    pricingVariant: 'cards',
    colorPalette: 'light',
    suggestedImages: ['estate planning', 'will', 'trust', 'family'],
    ctaText: 'Plan Your Estate',
    ctaTextEs: 'Planificar Patrimonio',
    keywords: ['estate', 'planning', 'will', 'patrimonio', 'testamento', 'herencia']
  },
  'intellectual-property': {
    id: 'intellectual-property',
    name: 'Intellectual Property Lawyer',
    nameEs: 'Abogado de Propiedad Intelectual',
    category: 'legal',
    sections: ['header', 'hero', 'about', 'features', 'process', 'stats', 'testimonials', 'faq', 'form', 'footer'],
    heroVariant: 'split',
    featuresVariant: 'grid',
    testimonialsVariant: 'featured',
    colorPalette: 'gradient',
    suggestedImages: ['intellectual property', 'patent', 'trademark', 'copyright'],
    ctaText: 'Protect Your IP',
    ctaTextEs: 'Proteger tu PI',
    keywords: ['intellectual property', 'patent', 'trademark', 'propiedad intelectual', 'patente', 'marca']
  }
};

// Exportar el conteo total de patrones extendidos
export const TOTAL_EXTENDED_PATTERNS = Object.keys(extendedIndustryPatterns).length;

// Función para obtener todos los patrones combinados
export function getAllIndustryPatterns(): Record<string, IndustryPattern> {
  // Importar dinámicamente para evitar dependencia circular
  const { industryPatterns } = require('./industryPatterns');
  return { ...industryPatterns, ...extendedIndustryPatterns };
}

// Función para buscar patrón por keywords en todos los patrones
export function findPatternByKeywordsExtended(query: string): IndustryPattern | null {
  const normalizedQuery = query.toLowerCase();
  const allPatterns = getAllIndustryPatterns();
  
  for (const pattern of Object.values(allPatterns)) {
    for (const keyword of pattern.keywords) {
      if (normalizedQuery.includes(keyword)) {
        return pattern;
      }
    }
  }
  
  return null;
}

// Lista de todas las categorías disponibles
export const EXTENDED_CATEGORIES = [
  'agriculture',
  'manufacturing', 
  'retail',
  'finance',
  'services',
  'health',
  'technology',
  'education',
  'entertainment',
  'sports',
  'home',
  'transportation',
  'media',
  'energy',
  'legal'
];
